BEGIN;

INSERT INTO settings (key, value, description)
VALUES
    ('REGION', '"BR"'::JSONB, 'Região principal utilizada na coleta e nas comparações.'),
    ('LANGUAGE', '"pt"'::JSONB, 'Idioma principal utilizado na coleta e classificação.'),
    ('COLLECTION_WINDOW_HOURS', '168'::JSONB, 'Janela inicial de coleta, em horas.'),
    ('MAX_RESULTS_PER_QUERY', '25'::JSONB, 'Limite inicial de resultados por query e grupo amostral.'),
    ('MAX_QUERIES_PER_RUN', '4'::JSONB, 'Quantidade máxima de combinações query e grupo processadas por execução.'),
    ('SHORT_MAX_DURATION', '180'::JSONB, 'Duração máxima, em segundos, para priorizar candidatos a Shorts.'),
    ('SNAPSHOT_ACTIVE_DAYS', '7'::JSONB, 'Quantidade inicial de dias de acompanhamento ativo.'),
    ('SNAPSHOT_RECENT_MAX_AGE_HOURS', '24'::JSONB, 'Limite de idade, em horas, da faixa de acompanhamento frequente.'),
    ('SNAPSHOT_INTERMEDIATE_MAX_AGE_HOURS', '72'::JSONB, 'Limite de idade, em horas, da faixa de acompanhamento intermediário.'),
    ('SNAPSHOT_RECENT_INTERVAL_MINUTES', '60'::JSONB, 'Intervalo mínimo, em minutos, entre snapshots de vídeos com até 24 horas.'),
    ('SNAPSHOT_INTERMEDIATE_INTERVAL_MINUTES', '360'::JSONB, 'Intervalo mínimo, em minutos, entre snapshots de vídeos com 1 a 3 dias.'),
    ('SNAPSHOT_OLDER_INTERVAL_MINUTES', '1440'::JSONB, 'Intervalo mínimo, em minutos, entre snapshots de vídeos com 3 a 7 dias.'),
    ('SNAPSHOT_MAX_VIDEOS_PER_RUN', '200'::JSONB, 'Quantidade máxima de vídeos atualizados por execução do Snapshot Tracker.'),
    ('SNAPSHOT_FAILURE_BACKOFF_BASE_MINUTES', '360'::JSONB, 'Espera inicial, em minutos, antes de tentar novamente um vídeo omitido por videos.list.'),
    ('SNAPSHOT_FAILURE_BACKOFF_MAX_MINUTES', '10080'::JSONB, 'Espera máxima, em minutos, aplicada a vídeos repetidamente omitidos por videos.list.'),
    ('COMMENT_WEIGHT', '3'::JSONB, 'Peso heurístico inicial dos comentários no Engagement Rate.'),
    ('LLM_MODEL', '"nvidia/llama-3.3-nemotron-super-49b-v1"'::JSONB, 'Modelo NVIDIA NIM utilizado inicialmente pelo classificador, sem armazenar credenciais.'),
    ('CLASSIFIER_MAX_VIDEOS_PER_RUN', '30'::JSONB, 'Quantidade máxima de vídeos classificados por execução.'),
    ('CLASSIFIER_DESCRIPTION_MAX_CHARS', '2000'::JSONB, 'Quantidade máxima de caracteres da descrição enviada ao classificador.'),
    ('CLASSIFIER_PROMPT_VERSION', '"v1"'::JSONB, 'Versão do prompt estruturado utilizado pelo classificador.'),
    ('CLASSIFIER_MAX_ATTEMPTS', '3'::JSONB, 'Quantidade máxima de falhas terminais automáticas antes de encaminhar o vídeo para revisão manual.'),
    ('CLASSIFIER_RETRY_BACKOFF_BASE_HOURS', '6'::JSONB, 'Espera inicial, em horas, antes de repetir uma classificação que falhou.'),
    ('CLASSIFIER_RETRY_BACKOFF_MAX_HOURS', '48'::JSONB, 'Espera máxima, em horas, aplicada ao backoff exponencial do classificador.'),
    ('LANGUAGE_GATE_MODEL', '"nvidia/llama-3.3-nemotron-super-49b-v1"'::JSONB, 'Modelo NVIDIA NIM usado somente para detectar idioma a partir de metadados públicos.'),
    ('LANGUAGE_GATE_PROMPT_VERSION', '"v1"'::JSONB, 'Versão do prompt estruturado do gate de idioma.'),
    ('LANGUAGE_GATE_MAX_VIDEOS_PER_RUN', '30'::JSONB, 'Quantidade máxima de vídeos avaliados por execução do gate de idioma.'),
    ('LANGUAGE_GATE_DESCRIPTION_MAX_CHARS', '1000'::JSONB, 'Quantidade máxima de caracteres da descrição enviada ao detector de idioma.'),
    ('LANGUAGE_GATE_MIN_CONFIDENCE', '0.80'::JSONB, 'Confiança mínima para aceitar ou rejeitar automaticamente um idioma detectado.'),
    ('LANGUAGE_GATE_MAX_ATTEMPTS', '3'::JSONB, 'Quantidade máxima de tentativas automáticas para metadados inconclusivos.'),
    ('LANGUAGE_GATE_RETRY_HOURS', '24'::JSONB, 'Espera antes de repetir uma detecção inconclusiva ou com erro.'),
    ('LANGUAGE_GATE_TARGET_LANGUAGE', '"pt"'::JSONB, 'Idioma primário desejado para a análise; não prova a variante regional.'),
    ('LANGUAGE_GATE_TARGET_REGION', '"BR"'::JSONB, 'Mercado-alvo operacional da coleta; não representa a origem comprovada do vídeo.'),
    ('METRICS_MAX_VIDEOS_PER_RUN', '1000'::JSONB, 'Quantidade máxima de vídeos cujas métricas atuais são recalculadas por execução.'),
    ('METRICS_ANALYSIS_WINDOW_DAYS', '7'::JSONB, 'Janela, em dias, usada para selecionar vídeos e formar coortes comparáveis.'),
    ('METRICS_CHANNEL_BASELINE_WINDOW_DAYS', '30'::JSONB, 'Janela recente, em dias, usada no baseline de visualizações do canal.'),
    ('METRICS_CHANNEL_BASELINE_MIN_VIDEOS', '3'::JSONB, 'Quantidade mínima de outros vídeos necessária para calcular o baseline do canal.'),
    ('METRICS_FRESHNESS_HORIZON_HOURS', '168'::JSONB, 'Horizonte, em horas, no qual o Freshness Score decai linearmente de 1 para 0.'),
    ('METRICS_MIN_VIRALITY_COMPONENTS', '3'::JSONB, 'Quantidade mínima de componentes disponíveis para calcular o Virality Score.'),
    ('METRICS_CALCULATION_VERSION', '"v1"'::JSONB, 'Versão das fórmulas do Metrics Engine e do Virality Score.'),
    ('VIRALITY_VELOCITY_WEIGHT', '0.35'::JSONB, 'Peso inicial do percentil de View Velocity no Virality Score.'),
    ('VIRALITY_ENGAGEMENT_WEIGHT', '0.20'::JSONB, 'Peso inicial do percentil de Engagement Rate no Virality Score.'),
    ('VIRALITY_OUTLIER_WEIGHT', '0.20'::JSONB, 'Peso inicial do percentil de Outlier Score no Virality Score.'),
    ('VIRALITY_VIEWS_WEIGHT', '0.15'::JSONB, 'Peso inicial do percentil de views no Virality Score.'),
    ('VIRALITY_FRESHNESS_WEIGHT', '0.10'::JSONB, 'Peso inicial do Freshness Score no Virality Score.'),
    ('MONETIZATION_MAX_VIDEOS_PER_RUN', '1000'::JSONB, 'Quantidade máxima de classificações recalculadas por execução do Monetization Engine.'),
    ('MONETIZATION_CALCULATION_VERSION', '"v1"'::JSONB, 'Versão das fórmulas e dos critérios heurísticos do Monetization Score.'),
    ('MONETIZATION_ORIGINALITY_WEIGHT', '0.30'::JSONB, 'Peso inicial da originalidade na base positiva do Monetization Score.'),
    ('MONETIZATION_POLICY_WEIGHT', '0.25'::JSONB, 'Peso inicial da elegibilidade de política na base positiva do Monetization Score.'),
    ('MONETIZATION_ADVERTISER_WEIGHT', '0.15'::JSONB, 'Peso inicial da adequação a anunciantes na base positiva do Monetization Score.'),
    ('MONETIZATION_PRODUCTION_WEIGHT', '0.15'::JSONB, 'Peso inicial da viabilidade de produção na base positiva do Monetization Score.'),
    ('MONETIZATION_ENGAGEMENT_WEIGHT', '0.15'::JSONB, 'Peso inicial da qualidade de engajamento na base positiva do Monetization Score.'),
    ('MONETIZATION_COPYRIGHT_RISK_WEIGHT', '0.60'::JSONB, 'Peso inicial do risco autoral na penalidade do Monetization Score.'),
    ('MONETIZATION_REUSED_RISK_WEIGHT', '0.40'::JSONB, 'Peso inicial do risco de conteúdo reutilizado na penalidade do Monetization Score.'),
    ('MONETIZATION_PRODUCTION_DURATION_WEIGHT', '0.30'::JSONB, 'Participação da duração observada no fator de viabilidade de produção.'),
    ('MONETIZATION_HIGH_RISK_THRESHOLD', '0.70'::JSONB, 'Limite inicial do risco combinado usado apenas para observabilidade.'),
    ('MONETIZATION_POLICY_SOURCE_SCORES', '{"original":1.0,"user_generated":0.9,"stock_media":0.8,"gameplay":0.75,"reaction":0.65,"podcast_clip":0.45,"third_party_content":0.35,"compilation":0.25,"movie_or_tv_clip":0.15,"unknown":0.5}'::JSONB, 'Mapa configurável de elegibilidade heurística por source_type.'),
    ('MONETIZATION_ADVERTISER_FORMAT_SCORES', '{"tutorial":0.95,"explainer":0.9,"curiosity":0.85,"comparison":0.85,"ranking":0.8,"storytelling":0.8,"motivation":0.85,"commentary":0.75,"news":0.65,"reaction":0.65,"meme":0.6,"clip":0.55,"compilation":0.55,"unknown":0.5}'::JSONB, 'Mapa configurável de adequação publicitária por formato inferido.'),
    ('MONETIZATION_PRODUCTION_FORMAT_SCORES', '{"clip":0.95,"meme":0.9,"reaction":0.85,"compilation":0.85,"ranking":0.8,"curiosity":0.75,"motivation":0.75,"commentary":0.7,"comparison":0.7,"news":0.7,"explainer":0.65,"storytelling":0.65,"tutorial":0.6,"unknown":0.5}'::JSONB, 'Mapa configurável de viabilidade de produção por formato inferido.'),
    ('TREND_PERIOD_HOURS', '168'::JSONB, 'Tamanho, em horas, das janelas atual e anterior comparadas pelo Trend Engine.'),
    ('TREND_BUCKET_MINUTES', '60'::JSONB, 'Tamanho do bucket temporal usado para tornar recálculos do Trend Engine idempotentes.'),
    ('TREND_MIN_SAMPLE_SIZE', '30'::JSONB, 'Amostra mínima por dimensão em cada janela para classificar a direção da tendência.'),
    ('TREND_CALCULATION_VERSION', '"v3-language-canonical"'::JSONB, 'Versão das agregações com português canônico em language e variantes preservadas em detected_language.'),
    ('TREND_OUTLIER_PERCENTILE_THRESHOLD', '0.90'::JSONB, 'Percentil mínimo de outlier usado para contabilizar outliers por grupo.'),
    ('TREND_HIGH_VIRALITY_THRESHOLD', '7.0'::JSONB, 'Virality Score mínimo usado para a taxa de alto desempenho.'),
    ('TREND_DIRECTION_CHANGE_THRESHOLD', '0.10'::JSONB, 'Variação mínima da mediana de Virality Score normalizada em 0 a 1 para rising ou declining.'),
    ('CONSISTENCY_SAMPLE_WEIGHT', '0.20'::JSONB, 'Peso da adequação do tamanho da amostra no Consistency Score.'),
    ('CONSISTENCY_P75_WEIGHT', '0.30'::JSONB, 'Peso da taxa de vídeos acima do percentil 75 no Consistency Score.'),
    ('CONSISTENCY_P90_WEIGHT', '0.20'::JSONB, 'Peso da taxa de vídeos acima do percentil 90 no Consistency Score.'),
    ('CONSISTENCY_ENGAGEMENT_WEIGHT', '0.20'::JSONB, 'Peso da mediana do percentil de engajamento no Consistency Score.'),
    ('CONSISTENCY_DISPERSION_WEIGHT', '0.10'::JSONB, 'Peso da estabilidade entre mediana e P90 de views no Consistency Score.'),
    ('OPPORTUNITY_CALCULATION_VERSION', '"v3-language-canonical"'::JSONB, 'Versão do ranking calculado sobre agregações com português analítico canônico.'),
    ('OPPORTUNITY_VIRALITY_WEIGHT', '0.50'::JSONB, 'Peso da mediana de Virality Score no Opportunity Score.'),
    ('OPPORTUNITY_MONETIZATION_WEIGHT', '0.35'::JSONB, 'Peso da mediana de Monetization Score no Opportunity Score.'),
    ('OPPORTUNITY_CONSISTENCY_WEIGHT', '0.15'::JSONB, 'Peso do Consistency Score no Opportunity Score.'),
    ('RECOMMENDATION_MAX_CATEGORIES_PER_RUN', '5'::JSONB, 'Quantidade máxima de categorias enviadas à IA por execução do Recommendation Engine.'),
    ('RECOMMENDATION_MIN_OPPORTUNITY_SCORE', '0'::JSONB, 'Opportunity Score mínimo para uma categoria se tornar candidata a recomendação.'),
    ('RECOMMENDATION_CONTEXT_LIMIT', '5'::JSONB, 'Quantidade máxima de padrões agregados por dimensão incluídos como contexto da IA.'),
    ('RECOMMENDATION_PROMPT_VERSION', '"v2"'::JSONB, 'Versão do prompt estruturado do Recommendation Engine.'),
    ('RECOMMENDATION_MODEL', '"nvidia/llama-3.3-nemotron-super-49b-v1"'::JSONB, 'Modelo NVIDIA NIM utilizado pelo Recommendation Engine, sem armazenar credenciais.'),
    ('MIN_SAMPLE_SIZE', '30'::JSONB, 'Amostra mínima obrigatória para categorias e padrões agregados enviados ao Recommendation AI.'),
    ('REPORT_PERIOD', '"7 days"'::JSONB, 'Período padrão dos relatórios agregados.'),
    ('REPORT_VERSION', '"v2"'::JSONB, 'Versão do contrato JSON e da apresentação Markdown do relatório.'),
    ('REPORT_TOP_OPPORTUNITIES_LIMIT', '5'::JSONB, 'Quantidade máxima de oportunidades exibidas no relatório.'),
    ('REPORT_VIRAL_RISK_LIMIT', '5'::JSONB, 'Quantidade máxima de categorias virais com risco de monetização exibidas no relatório.'),
    ('REPORT_EMERGING_TRENDS_LIMIT', '5'::JSONB, 'Quantidade máxima de tendências emergentes exibidas no relatório.'),
    ('REPORT_VIRALITY_RISK_MIN', '6'::JSONB, 'Mediana mínima de Virality Score para a seção Viral but Risky.'),
    ('REPORT_MONETIZATION_RISK_MAX', '5'::JSONB, 'Mediana máxima de Monetization Score para a seção Viral but Risky.'),
    ('REPORT_TIMEZONE', '"America/Sao_Paulo"'::JSONB, 'Fuso horário usado para apresentar datas no relatório Markdown.'),
    ('OBSERVABILITY_PERIOD', '"24 hours"'::JSONB, 'Janela fechada usada pelos relatórios de observabilidade.'),
    ('OBSERVABILITY_VERSION', '"v2-language-eligible"'::JSONB, 'Versão da observabilidade com o gate de idioma e indicadores analíticos filtrados.'),
    ('OBSERVABILITY_STALE_RUN_MINUTES', '120'::JSONB, 'Tempo máximo, em minutos, para uma execução permanecer running.'),
    ('OBSERVABILITY_HIGH_VIRALITY_THRESHOLD', '7'::JSONB, 'Virality Score mínimo para contabilizar vídeos de alta viralidade.'),
    ('OBSERVABILITY_HIGH_OPPORTUNITY_THRESHOLD', '7'::JSONB, 'Opportunity Score mínimo para destacar categorias.'),
    ('OBSERVABILITY_ERROR_LIMIT', '20'::JSONB, 'Quantidade máxima de eventos recentes incluídos no relatório.'),
    ('OBSERVABILITY_TIMEZONE', '"America/Sao_Paulo"'::JSONB, 'Fuso horário de referência da observabilidade.'),
    ('VALIDATION_PERIOD', '"7 days"'::JSONB, 'Janela observacional usada pela validação da Fase 12.'),
    ('VALIDATION_VERSION', '"v2-language-eligible"'::JSONB, 'Versão da validação restrita aos vídeos linguisticamente elegíveis.'),
    ('VALIDATION_MIN_OBSERVATION_DAYS', '3'::JSONB, 'Quantidade mínima de dias entre o primeiro e o último snapshot da janela.'),
    ('VALIDATION_MIN_CATEGORY_SAMPLE_SIZE', '30'::JSONB, 'Amostra mínima por categoria para revisar pesos.'),
    ('VALIDATION_MIN_CLASSIFIER_REVIEWS', '30'::JSONB, 'Quantidade mínima de revisões humanas concluídas do classificador.'),
    ('VALIDATION_CLASSIFIER_CONFIDENCE_FLOOR', '0.65'::JSONB, 'Confiança abaixo da qual uma classificação recebe atenção adicional.'),
    ('VALIDATION_SCORE_TAIL_THRESHOLD', '0.10'::JSONB, 'Taxa máxima esperada em cada cauda extrema dos scores.'),
    ('VALIDATION_SNAPSHOT_CADENCE_TOLERANCE', '1.50'::JSONB, 'Multiplicador tolerado sobre o intervalo esperado entre snapshots.'),
    ('YOUTUBE_QUOTA_BUDGET_PER_RUN', '1000'::JSONB, 'Orçamento máximo estimado para operações do bucket geral por execução.'),
    ('YOUTUBE_SEARCH_DAILY_CALL_LIMIT', '100'::JSONB, 'Limite diário configurável do bucket separado de search.list.'),
    ('YOUTUBE_SEARCH_QUOTA_COST', '1'::JSONB, 'Custo configurável de uma chamada search.list em seu bucket separado.'),
    ('YOUTUBE_VIDEOS_LIST_QUOTA_COST', '1'::JSONB, 'Custo configurável estimado de uma chamada videos.list.')
ON CONFLICT (key) DO UPDATE
SET
    value = EXCLUDED.value,
    description = EXCLUDED.description;

COMMIT;
