BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT categories_slug_format_check
        CHECK (slug ~ '^[a-z0-9]+(?:_[a-z0-9]+)*$')
);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    description TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT settings_key_format_check
        CHECK (key ~ '^[A-Z][A-Z0-9_]*$')
);

CREATE TABLE IF NOT EXISTS collection_queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    query_text TEXT NOT NULL,
    sample_group TEXT NOT NULL,
    language VARCHAR(16) NOT NULL DEFAULT 'pt',
    region CHAR(2) NOT NULL DEFAULT 'BR',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    priority SMALLINT NOT NULL DEFAULT 100,
    max_results_override INTEGER,
    last_collected_at TIMESTAMPTZ,
    last_status TEXT,
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    total_runs BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT collection_queries_query_text_check
        CHECK (length(btrim(query_text)) > 0),
    CONSTRAINT collection_queries_sample_group_check
        CHECK (sample_group IN ('recent', 'high_performance')),
    CONSTRAINT collection_queries_region_check
        CHECK (region = upper(region)),
    CONSTRAINT collection_queries_priority_check
        CHECK (priority >= 0),
    CONSTRAINT collection_queries_max_results_check
        CHECK (max_results_override IS NULL OR max_results_override > 0),
    CONSTRAINT collection_queries_last_status_check
        CHECK (last_status IS NULL OR last_status IN ('success', 'partial', 'failed', 'skipped')),
    CONSTRAINT collection_queries_consecutive_failures_check
        CHECK (consecutive_failures >= 0),
    CONSTRAINT collection_queries_total_runs_check
        CHECK (total_runs >= 0)
);

CREATE TABLE IF NOT EXISTS videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform TEXT NOT NULL,
    external_id TEXT NOT NULL,
    channel_id TEXT NOT NULL,
    channel_name TEXT,
    title TEXT NOT NULL,
    description TEXT,
    url TEXT NOT NULL,
    published_at TIMESTAMPTZ NOT NULL,
    duration_seconds INTEGER,
    language VARCHAR(16),
    region CHAR(2),
    short_confidence TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT videos_platform_external_id_unique
        UNIQUE (platform, external_id),
    CONSTRAINT videos_platform_format_check
        CHECK (platform ~ '^[a-z0-9_]+$'),
    CONSTRAINT videos_external_id_check
        CHECK (length(btrim(external_id)) > 0),
    CONSTRAINT videos_duration_check
        CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
    CONSTRAINT videos_region_check
        CHECK (region IS NULL OR region = upper(region)),
    CONSTRAINT videos_short_confidence_check
        CHECK (short_confidence IN ('high', 'medium', 'low'))
);

CREATE TABLE IF NOT EXISTS video_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id BIGINT NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    collected_at TIMESTAMPTZ NOT NULL,
    views BIGINT NOT NULL,
    likes BIGINT,
    comments BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT video_snapshots_video_collected_unique
        UNIQUE (video_id, collected_at),
    CONSTRAINT video_snapshots_views_check
        CHECK (views >= 0),
    CONSTRAINT video_snapshots_likes_check
        CHECK (likes IS NULL OR likes >= 0),
    CONSTRAINT video_snapshots_comments_check
        CHECK (comments IS NULL OR comments >= 0)
);

CREATE TABLE IF NOT EXISTS video_classifications (
    video_id BIGINT PRIMARY KEY REFERENCES videos(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    topic TEXT NOT NULL,
    content_type TEXT NOT NULL,
    format TEXT NOT NULL,
    hook_type TEXT NOT NULL,
    source_type TEXT NOT NULL,
    presentation_style TEXT NOT NULL,
    originality_score NUMERIC(5, 4) NOT NULL,
    copyright_risk NUMERIC(5, 4) NOT NULL,
    reused_content_risk NUMERIC(5, 4) NOT NULL,
    ai_confidence NUMERIC(5, 4) NOT NULL,
    classification_model TEXT NOT NULL,
    prompt_version TEXT NOT NULL DEFAULT 'v1',
    classified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT video_classifications_topic_check
        CHECK (topic ~ '^[a-z0-9_]+$'),
    CONSTRAINT video_classifications_content_type_check
        CHECK (content_type ~ '^[a-z0-9_]+$'),
    CONSTRAINT video_classifications_format_check
        CHECK (format ~ '^[a-z0-9_]+$'),
    CONSTRAINT video_classifications_hook_type_check
        CHECK (hook_type ~ '^[a-z0-9_]+$'),
    CONSTRAINT video_classifications_source_type_check
        CHECK (source_type ~ '^[a-z0-9_]+$'),
    CONSTRAINT video_classifications_presentation_style_check
        CHECK (presentation_style ~ '^[a-z0-9_]+$'),
    CONSTRAINT video_classifications_originality_check
        CHECK (originality_score BETWEEN 0 AND 1),
    CONSTRAINT video_classifications_copyright_risk_check
        CHECK (copyright_risk BETWEEN 0 AND 1),
    CONSTRAINT video_classifications_reused_risk_check
        CHECK (reused_content_risk BETWEEN 0 AND 1),
    CONSTRAINT video_classifications_confidence_check
        CHECK (ai_confidence BETWEEN 0 AND 1)
);

CREATE TABLE IF NOT EXISTS video_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id BIGINT NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    snapshot_id BIGINT NOT NULL UNIQUE REFERENCES video_snapshots(id) ON DELETE CASCADE,
    previous_snapshot_id BIGINT REFERENCES video_snapshots(id) ON DELETE SET NULL,
    like_rate NUMERIC(18, 8),
    comment_rate NUMERIC(18, 8),
    engagement_rate NUMERIC(18, 8),
    view_velocity NUMERIC(20, 6),
    view_acceleration NUMERIC(20, 6),
    channel_median_views NUMERIC(20, 4),
    relative_performance NUMERIC(20, 8),
    outlier_score NUMERIC(20, 8),
    velocity_percentile NUMERIC(5, 4),
    engagement_percentile NUMERIC(5, 4),
    outlier_percentile NUMERIC(5, 4),
    views_percentile NUMERIC(5, 4),
    freshness_score NUMERIC(5, 4),
    virality_score NUMERIC(6, 4),
    calculation_version TEXT NOT NULL DEFAULT 'v1',
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT video_metrics_like_rate_check
        CHECK (like_rate IS NULL OR like_rate >= 0),
    CONSTRAINT video_metrics_comment_rate_check
        CHECK (comment_rate IS NULL OR comment_rate >= 0),
    CONSTRAINT video_metrics_engagement_rate_check
        CHECK (engagement_rate IS NULL OR engagement_rate >= 0),
    CONSTRAINT video_metrics_channel_median_check
        CHECK (channel_median_views IS NULL OR channel_median_views >= 0),
    CONSTRAINT video_metrics_relative_performance_check
        CHECK (relative_performance IS NULL OR relative_performance >= 0),
    CONSTRAINT video_metrics_outlier_score_check
        CHECK (outlier_score IS NULL OR outlier_score >= 0),
    CONSTRAINT video_metrics_velocity_percentile_check
        CHECK (velocity_percentile IS NULL OR velocity_percentile BETWEEN 0 AND 1),
    CONSTRAINT video_metrics_engagement_percentile_check
        CHECK (engagement_percentile IS NULL OR engagement_percentile BETWEEN 0 AND 1),
    CONSTRAINT video_metrics_outlier_percentile_check
        CHECK (outlier_percentile IS NULL OR outlier_percentile BETWEEN 0 AND 1),
    CONSTRAINT video_metrics_views_percentile_check
        CHECK (views_percentile IS NULL OR views_percentile BETWEEN 0 AND 1),
    CONSTRAINT video_metrics_freshness_check
        CHECK (freshness_score IS NULL OR freshness_score BETWEEN 0 AND 1),
    CONSTRAINT video_metrics_virality_check
        CHECK (virality_score IS NULL OR virality_score BETWEEN 0 AND 10)
);

CREATE TABLE IF NOT EXISTS video_monetization_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id BIGINT NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    originality NUMERIC(5, 4) NOT NULL,
    policy_eligibility NUMERIC(5, 4) NOT NULL,
    advertiser_suitability NUMERIC(5, 4) NOT NULL,
    production_feasibility NUMERIC(5, 4) NOT NULL,
    engagement_quality NUMERIC(5, 4) NOT NULL,
    copyright_risk NUMERIC(5, 4) NOT NULL,
    reused_content_risk NUMERIC(5, 4) NOT NULL,
    monetization_score NUMERIC(6, 4) NOT NULL,
    calculation_version TEXT NOT NULL DEFAULT 'v1',
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT video_monetization_video_version_unique
        UNIQUE (video_id, calculation_version),
    CONSTRAINT video_monetization_originality_check
        CHECK (originality BETWEEN 0 AND 1),
    CONSTRAINT video_monetization_policy_check
        CHECK (policy_eligibility BETWEEN 0 AND 1),
    CONSTRAINT video_monetization_advertiser_check
        CHECK (advertiser_suitability BETWEEN 0 AND 1),
    CONSTRAINT video_monetization_production_check
        CHECK (production_feasibility BETWEEN 0 AND 1),
    CONSTRAINT video_monetization_engagement_check
        CHECK (engagement_quality BETWEEN 0 AND 1),
    CONSTRAINT video_monetization_copyright_check
        CHECK (copyright_risk BETWEEN 0 AND 1),
    CONSTRAINT video_monetization_reused_check
        CHECK (reused_content_risk BETWEEN 0 AND 1),
    CONSTRAINT video_monetization_score_check
        CHECK (monetization_score BETWEEN 0 AND 10)
);

CREATE TABLE IF NOT EXISTS category_statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    platform TEXT NOT NULL,
    region CHAR(2),
    language VARCHAR(16),
    topic TEXT,
    content_type TEXT,
    format TEXT,
    hook_type TEXT,
    source_type TEXT,
    sample_size INTEGER NOT NULL,
    median_views NUMERIC(20, 4),
    p75_views NUMERIC(20, 4),
    p90_views NUMERIC(20, 4),
    median_engagement NUMERIC(18, 8),
    median_velocity NUMERIC(20, 6),
    median_virality NUMERIC(6, 4),
    median_monetization NUMERIC(6, 4),
    outlier_count INTEGER NOT NULL DEFAULT 0,
    outlier_rate NUMERIC(5, 4),
    high_performance_rate NUMERIC(5, 4),
    consistency_score NUMERIC(6, 4),
    saturation_score NUMERIC(5, 4),
    opportunity_score NUMERIC(6, 4),
    trend_direction TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT category_statistics_period_check
        CHECK (period_end > period_start),
    CONSTRAINT category_statistics_sample_size_check
        CHECK (sample_size >= 0),
    CONSTRAINT category_statistics_outlier_count_check
        CHECK (outlier_count >= 0 AND outlier_count <= sample_size),
    CONSTRAINT category_statistics_outlier_rate_check
        CHECK (outlier_rate IS NULL OR outlier_rate BETWEEN 0 AND 1),
    CONSTRAINT category_statistics_high_performance_check
        CHECK (high_performance_rate IS NULL OR high_performance_rate BETWEEN 0 AND 1),
    CONSTRAINT category_statistics_consistency_check
        CHECK (consistency_score IS NULL OR consistency_score BETWEEN 0 AND 10),
    CONSTRAINT category_statistics_saturation_check
        CHECK (saturation_score IS NULL OR saturation_score BETWEEN 0 AND 1),
    CONSTRAINT category_statistics_opportunity_check
        CHECK (opportunity_score IS NULL OR opportunity_score BETWEEN 0 AND 10),
    CONSTRAINT category_statistics_trend_check
        CHECK (trend_direction IN ('rising', 'stable', 'declining', 'insufficient_data'))
);

CREATE TABLE IF NOT EXISTS recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    opportunity_score NUMERIC(6, 4) NOT NULL,
    virality_score NUMERIC(6, 4) NOT NULL,
    monetization_score NUMERIC(6, 4) NOT NULL,
    summary TEXT NOT NULL,
    recommended_formats TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    recommended_hooks TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    risks TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    monetization_notes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    evidence_json JSONB NOT NULL,
    model TEXT NOT NULL,
    CONSTRAINT recommendations_period_check
        CHECK (period_end > period_start),
    CONSTRAINT recommendations_opportunity_check
        CHECK (opportunity_score BETWEEN 0 AND 10),
    CONSTRAINT recommendations_virality_check
        CHECK (virality_score BETWEEN 0 AND 10),
    CONSTRAINT recommendations_monetization_check
        CHECK (monetization_score BETWEEN 0 AND 10),
    CONSTRAINT recommendations_evidence_object_check
        CHECK (jsonb_typeof(evidence_json) = 'object')
);

CREATE TABLE IF NOT EXISTS pipeline_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    status TEXT NOT NULL,
    items_received INTEGER NOT NULL DEFAULT 0,
    items_processed INTEGER NOT NULL DEFAULT 0,
    items_skipped INTEGER NOT NULL DEFAULT 0,
    items_failed INTEGER NOT NULL DEFAULT 0,
    api_calls INTEGER NOT NULL DEFAULT 0,
    quota_units_estimated INTEGER NOT NULL DEFAULT 0,
    duration_seconds NUMERIC(14, 3),
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT pipeline_runs_status_check
        CHECK (status IN ('running', 'success', 'partial', 'failed', 'cancelled')),
    CONSTRAINT pipeline_runs_items_received_check
        CHECK (items_received >= 0),
    CONSTRAINT pipeline_runs_items_processed_check
        CHECK (items_processed >= 0),
    CONSTRAINT pipeline_runs_items_skipped_check
        CHECK (items_skipped >= 0),
    CONSTRAINT pipeline_runs_items_failed_check
        CHECK (items_failed >= 0),
    CONSTRAINT pipeline_runs_api_calls_check
        CHECK (api_calls >= 0),
    CONSTRAINT pipeline_runs_quota_check
        CHECK (quota_units_estimated >= 0),
    CONSTRAINT pipeline_runs_duration_check
        CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
    CONSTRAINT pipeline_runs_time_check
        CHECK (finished_at IS NULL OR finished_at >= started_at),
    CONSTRAINT pipeline_runs_metadata_object_check
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE IF NOT EXISTS pipeline_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_id BIGINT REFERENCES pipeline_runs(id) ON DELETE SET NULL,
    workflow TEXT NOT NULL,
    node TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    error_type TEXT NOT NULL,
    error_message TEXT NOT NULL,
    external_id TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT pipeline_errors_retry_count_check
        CHECK (retry_count >= 0),
    CONSTRAINT pipeline_errors_metadata_object_check
        CHECK (jsonb_typeof(metadata) = 'object')
);

DROP TRIGGER IF EXISTS categories_set_updated_at ON categories;
CREATE TRIGGER categories_set_updated_at
BEFORE UPDATE ON categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS settings_set_updated_at ON settings;
CREATE TRIGGER settings_set_updated_at
BEFORE UPDATE ON settings
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS collection_queries_set_updated_at ON collection_queries;
CREATE TRIGGER collection_queries_set_updated_at
BEFORE UPDATE ON collection_queries
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS videos_set_updated_at ON videos;
CREATE TRIGGER videos_set_updated_at
BEFORE UPDATE ON videos
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;
