BEGIN;

CREATE TABLE IF NOT EXISTS video_collection_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_id BIGINT NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,
    collection_query_id BIGINT NOT NULL REFERENCES collection_queries(id) ON DELETE RESTRICT,
    video_id BIGINT NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    search_rank INTEGER NOT NULL,
    matched_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT video_collection_matches_identity_unique
        UNIQUE (pipeline_run_id, collection_query_id, video_id),
    CONSTRAINT video_collection_matches_search_rank_check
        CHECK (search_rank > 0)
);

CREATE INDEX IF NOT EXISTS video_collection_matches_query_idx
    ON video_collection_matches (collection_query_id, matched_at DESC);

CREATE INDEX IF NOT EXISTS video_collection_matches_video_idx
    ON video_collection_matches (video_id, matched_at DESC);

COMMIT;
