BEGIN;

INSERT INTO settings (key, value, description)
VALUES
    ('REPORT_PERIOD', '"7 days"'::JSONB, 'Período padrão dos relatórios agregados.'),
    ('REPORT_VERSION', '"v2"'::JSONB, 'Versão do contrato JSON e da apresentação Markdown do relatório.'),
    ('REPORT_TOP_OPPORTUNITIES_LIMIT', '5'::JSONB, 'Quantidade máxima de oportunidades exibidas no relatório.'),
    ('REPORT_VIRAL_RISK_LIMIT', '5'::JSONB, 'Quantidade máxima de categorias virais com risco de monetização exibidas no relatório.'),
    ('REPORT_EMERGING_TRENDS_LIMIT', '5'::JSONB, 'Quantidade máxima de tendências emergentes exibidas no relatório.'),
    ('REPORT_VIRALITY_RISK_MIN', '6'::JSONB, 'Mediana mínima de Virality Score para a seção Viral but Risky.'),
    ('REPORT_MONETIZATION_RISK_MAX', '5'::JSONB, 'Mediana máxima de Monetization Score para a seção Viral but Risky.'),
    ('REPORT_TIMEZONE', '"America/Sao_Paulo"'::JSONB, 'Fuso horário usado para apresentar datas no relatório Markdown.')
ON CONFLICT (key) DO UPDATE
SET description = EXCLUDED.description;

UPDATE settings
   SET value = '"v2"'::JSONB
 WHERE key = 'REPORT_VERSION'
   AND value = '"v1"'::JSONB;

CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    platform TEXT NOT NULL,
    region CHAR(2),
    language VARCHAR(16),
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    report_version TEXT NOT NULL,
    source_calculation_version TEXT NOT NULL,
    source_opportunity_version TEXT NOT NULL,
    recommendation_prompt_version TEXT NOT NULL,
    videos_analyzed INTEGER NOT NULL,
    categories_analyzed INTEGER NOT NULL,
    top_opportunities_count INTEGER NOT NULL,
    viral_but_risky_count INTEGER NOT NULL,
    emerging_trends_count INTEGER NOT NULL,
    report_json JSONB NOT NULL,
    report_markdown TEXT NOT NULL,
    source_hash TEXT NOT NULL,
    CONSTRAINT reports_period_check
        CHECK (period_end > period_start),
    CONSTRAINT reports_version_check
        CHECK (length(btrim(report_version)) > 0),
    CONSTRAINT reports_source_versions_check
        CHECK (
            length(btrim(source_calculation_version)) > 0
            AND length(btrim(source_opportunity_version)) > 0
            AND length(btrim(recommendation_prompt_version)) > 0
        ),
    CONSTRAINT reports_counts_check
        CHECK (
            videos_analyzed >= 0
            AND categories_analyzed >= 0
            AND top_opportunities_count >= 0
            AND viral_but_risky_count >= 0
            AND emerging_trends_count >= 0
        ),
    CONSTRAINT reports_json_object_check
        CHECK (jsonb_typeof(report_json) = 'object'),
    CONSTRAINT reports_json_sections_check
        CHECK (
            report_json ? 'period'
            AND report_json ? 'coverage'
            AND report_json ? 'top_opportunities'
            AND report_json ? 'viral_but_risky'
            AND report_json ? 'emerging_trends'
        ),
    CONSTRAINT reports_markdown_check
        CHECK (length(btrim(report_markdown)) > 0),
    CONSTRAINT reports_source_hash_check
        CHECK (source_hash ~ '^[a-f0-9]{32}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS reports_source_version_idx
    ON reports (
        period_start,
        period_end,
        platform,
        region,
        language,
        report_version,
        source_calculation_version,
        source_opportunity_version,
        recommendation_prompt_version,
        source_hash
    )
    NULLS NOT DISTINCT;

CREATE INDEX IF NOT EXISTS reports_generated_context_idx
    ON reports (generated_at DESC, platform, region, language);

CREATE OR REPLACE FUNCTION build_trendlens_report(
    p_generated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)
RETURNS TABLE (
    period_start TIMESTAMPTZ,
    period_end TIMESTAMPTZ,
    platform TEXT,
    region CHAR(2),
    language VARCHAR(16),
    generated_at TIMESTAMPTZ,
    report_version TEXT,
    source_calculation_version TEXT,
    source_opportunity_version TEXT,
    recommendation_prompt_version TEXT,
    videos_analyzed INTEGER,
    categories_analyzed INTEGER,
    top_opportunities_count INTEGER,
    viral_but_risky_count INTEGER,
    emerging_trends_count INTEGER,
    report_json JSONB,
    report_markdown TEXT,
    source_hash TEXT
)
LANGUAGE sql
STABLE
AS $$
WITH config AS (
    SELECT
        'youtube'::TEXT AS platform,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'REGION'), ''), 'BR')::CHAR(2) AS region,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'LANGUAGE'), ''), 'pt')::VARCHAR(16) AS language,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'REPORT_VERSION'), ''), 'v2') AS report_version,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'TREND_CALCULATION_VERSION'), ''), 'v1') AS trend_version,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'OPPORTUNITY_CALCULATION_VERSION'), ''), 'v1') AS opportunity_version,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'RECOMMENDATION_PROMPT_VERSION'), ''), 'v2') AS recommendation_prompt_version,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'REPORT_TIMEZONE'), ''), 'America/Sao_Paulo') AS report_timezone,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'REPORT_PERIOD'), '')::INTERVAL, INTERVAL '7 days') AS report_period,
        GREATEST(1, LEAST(20, COALESCE((SELECT (value #>> '{}')::INTEGER FROM settings WHERE key = 'REPORT_TOP_OPPORTUNITIES_LIMIT'), 5))) AS top_limit,
        GREATEST(1, LEAST(20, COALESCE((SELECT (value #>> '{}')::INTEGER FROM settings WHERE key = 'REPORT_VIRAL_RISK_LIMIT'), 5))) AS viral_risk_limit,
        GREATEST(1, LEAST(20, COALESCE((SELECT (value #>> '{}')::INTEGER FROM settings WHERE key = 'REPORT_EMERGING_TRENDS_LIMIT'), 5))) AS emerging_limit,
        GREATEST(0::NUMERIC, LEAST(10::NUMERIC, COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'REPORT_VIRALITY_RISK_MIN'), 6))) AS virality_risk_min,
        GREATEST(0::NUMERIC, LEAST(10::NUMERIC, COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'REPORT_MONETIZATION_RISK_MAX'), 5))) AS monetization_risk_max
), selected_context AS (
    SELECT
        config.platform,
        config.region,
        COALESCE((
            SELECT statistic.language
              FROM category_statistics statistic
             WHERE statistic.platform = config.platform
               AND statistic.region IS NOT DISTINCT FROM config.region
               AND statistic.calculation_version = config.trend_version
               AND statistic.dimension_type = 'category'
               AND statistic.opportunity_score IS NOT NULL
               AND statistic.opportunity_calculation_version = config.opportunity_version
               AND (
                   statistic.language = config.language
                   OR statistic.language LIKE config.language || '-%'
               )
             GROUP BY statistic.language
             ORDER BY
                 (statistic.language = config.language) DESC,
                 count(*) DESC,
                 sum(statistic.sample_size) DESC,
                 statistic.language
             LIMIT 1
        ), config.language)::VARCHAR(16) AS language,
        config.language AS requested_language
      FROM config
), latest_period AS (
    SELECT max(statistic.period_end) AS period_end
      FROM category_statistics statistic
      CROSS JOIN config
      CROSS JOIN selected_context
     WHERE statistic.platform = selected_context.platform
       AND statistic.region IS NOT DISTINCT FROM selected_context.region
       AND statistic.language IS NOT DISTINCT FROM selected_context.language
       AND statistic.calculation_version = config.trend_version
       AND statistic.dimension_type = 'category'
       AND statistic.opportunity_score IS NOT NULL
       AND statistic.opportunity_calculation_version = config.opportunity_version
), bounds AS (
    SELECT
        COALESCE((
            SELECT max(statistic.period_start)
              FROM category_statistics statistic
             WHERE statistic.period_end = latest_period.period_end
               AND statistic.platform = selected_context.platform
               AND statistic.region IS NOT DISTINCT FROM selected_context.region
               AND statistic.language IS NOT DISTINCT FROM selected_context.language
               AND statistic.calculation_version = config.trend_version
               AND statistic.dimension_type = 'category'
        ), p_generated_at - config.report_period) AS period_start,
        COALESCE(latest_period.period_end, p_generated_at) AS period_end
      FROM config
      CROSS JOIN selected_context
      CROSS JOIN latest_period
), base AS (
    SELECT
        statistic.*,
        recommendation.id AS recommendation_id,
        recommendation.summary AS recommendation_summary,
        recommendation.recommended_formats,
        recommendation.recommended_hooks,
        recommendation.risks AS recommendation_risks,
        recommendation.monetization_notes,
        recommendation.model AS recommendation_model,
        recommendation.prompt_version AS used_prompt_version,
        recommendation.generated_at AS recommendation_generated_at
      FROM category_statistics statistic
      CROSS JOIN config
      CROSS JOIN selected_context
      CROSS JOIN latest_period
      LEFT JOIN LATERAL (
          SELECT candidate.*
            FROM recommendations candidate
           WHERE candidate.category = statistic.category_slug
             AND candidate.period_start = statistic.period_start
             AND candidate.period_end = statistic.period_end
             AND candidate.platform = statistic.platform
             AND candidate.region IS NOT DISTINCT FROM statistic.region
             AND candidate.language IS NOT DISTINCT FROM statistic.language
             AND candidate.source_calculation_version = statistic.calculation_version
             AND candidate.source_opportunity_version = statistic.opportunity_calculation_version
             AND candidate.prompt_version = config.recommendation_prompt_version
           ORDER BY candidate.generated_at DESC, candidate.id DESC
           LIMIT 1
      ) recommendation ON TRUE
     WHERE latest_period.period_end IS NOT NULL
       AND statistic.period_end = latest_period.period_end
       AND statistic.platform = selected_context.platform
       AND statistic.region IS NOT DISTINCT FROM selected_context.region
       AND statistic.language IS NOT DISTINCT FROM selected_context.language
       AND statistic.calculation_version = config.trend_version
       AND statistic.dimension_type = 'category'
), coverage AS (
    SELECT
        COALESCE(sum(base.sample_size), 0)::INTEGER AS videos_analyzed,
        count(base.id)::INTEGER AS categories_analyzed,
        count(base.id) FILTER (WHERE base.opportunity_score IS NOT NULL)::INTEGER AS categories_with_opportunity,
        count(base.id) FILTER (WHERE base.recommendation_id IS NOT NULL)::INTEGER AS recommendations_available,
        count(base.id) FILTER (WHERE base.used_prompt_version = config.recommendation_prompt_version)::INTEGER AS current_prompt_recommendations
      FROM config
      LEFT JOIN base ON TRUE
), opportunity_ranked AS (
    SELECT
        base.*,
        row_number() OVER (
            ORDER BY base.opportunity_score DESC, base.opportunity_rank, base.category_slug
        )::INTEGER AS display_rank
      FROM base
     WHERE base.opportunity_score IS NOT NULL
), top_rows AS (
    SELECT opportunity_ranked.*
      FROM opportunity_ranked
      CROSS JOIN config
     WHERE opportunity_ranked.display_rank <= config.top_limit
), risky_ranked AS (
    SELECT
        base.*,
        round(base.median_virality - base.median_monetization, 4) AS risk_gap,
        row_number() OVER (
            ORDER BY
                (base.median_virality - base.median_monetization) DESC,
                base.median_virality DESC,
                base.category_slug
        )::INTEGER AS display_rank
      FROM base
      CROSS JOIN config
     WHERE base.median_virality >= config.virality_risk_min
       AND base.median_monetization <= config.monetization_risk_max
), risky_rows AS (
    SELECT risky_ranked.*
      FROM risky_ranked
      CROSS JOIN config
     WHERE risky_ranked.display_rank <= config.viral_risk_limit
), emerging_ranked AS (
    SELECT
        base.*,
        row_number() OVER (
            ORDER BY base.trend_change DESC NULLS LAST, base.opportunity_score DESC, base.category_slug
        )::INTEGER AS display_rank
      FROM base
     WHERE base.trend_direction = 'rising'
), emerging_rows AS (
    SELECT emerging_ranked.*
      FROM emerging_ranked
      CROSS JOIN config
     WHERE emerging_ranked.display_rank <= config.emerging_limit
), top_section AS (
    SELECT
        COALESCE(jsonb_agg(
            jsonb_build_object(
                'rank', top_rows.display_rank,
                'category', top_rows.category_slug,
                'opportunity_score', top_rows.opportunity_score,
                'virality_score', top_rows.median_virality,
                'monetization_score', top_rows.median_monetization,
                'consistency_score', top_rows.consistency_score,
                'evidence', jsonb_build_object(
                    'sample_size', top_rows.sample_size,
                    'previous_sample_size', top_rows.previous_sample_size,
                    'median_views', top_rows.median_views,
                    'p75_views', top_rows.p75_views,
                    'p90_views', top_rows.p90_views,
                    'median_engagement_rate', top_rows.median_engagement,
                    'median_view_velocity', top_rows.median_velocity,
                    'outlier_rate', top_rows.outlier_rate,
                    'high_performance_rate', top_rows.high_performance_rate,
                    'trend_direction', top_rows.trend_direction,
                    'trend_change', top_rows.trend_change
                ),
                'recommendation', CASE
                    WHEN top_rows.recommendation_id IS NULL THEN NULL
                    ELSE jsonb_build_object(
                        'summary', top_rows.recommendation_summary,
                        'recommended_formats', top_rows.recommended_formats,
                        'recommended_hooks', top_rows.recommended_hooks,
                        'risks', top_rows.recommendation_risks,
                        'monetization_notes', top_rows.monetization_notes,
                        'model', top_rows.recommendation_model,
                        'prompt_version', top_rows.used_prompt_version,
                        'is_current_prompt', top_rows.used_prompt_version = config.recommendation_prompt_version
                    )
                END
            )
            ORDER BY top_rows.display_rank
        ) FILTER (WHERE top_rows.category_slug IS NOT NULL), '[]'::JSONB) AS items,
        count(top_rows.category_slug)::INTEGER AS item_count
      FROM config
      LEFT JOIN top_rows ON TRUE
), risky_section AS (
    SELECT
        COALESCE(jsonb_agg(
            jsonb_build_object(
                'rank', risky_rows.display_rank,
                'category', risky_rows.category_slug,
                'virality_score', risky_rows.median_virality,
                'monetization_score', risky_rows.median_monetization,
                'risk_gap', risky_rows.risk_gap,
                'sample_size', risky_rows.sample_size,
                'outlier_rate', risky_rows.outlier_rate,
                'risks', COALESCE(to_jsonb(risky_rows.recommendation_risks), '[]'::JSONB)
            )
            ORDER BY risky_rows.display_rank
        ) FILTER (WHERE risky_rows.category_slug IS NOT NULL), '[]'::JSONB) AS items,
        count(risky_rows.category_slug)::INTEGER AS item_count
      FROM risky_rows
      RIGHT JOIN config ON TRUE
), emerging_section AS (
    SELECT
        COALESCE(jsonb_agg(
            jsonb_build_object(
                'rank', emerging_rows.display_rank,
                'category', emerging_rows.category_slug,
                'trend_direction', emerging_rows.trend_direction,
                'trend_change', emerging_rows.trend_change,
                'sample_size', emerging_rows.sample_size,
                'previous_sample_size', emerging_rows.previous_sample_size,
                'opportunity_score', emerging_rows.opportunity_score,
                'virality_score', emerging_rows.median_virality
            )
            ORDER BY emerging_rows.display_rank
        ) FILTER (WHERE emerging_rows.category_slug IS NOT NULL), '[]'::JSONB) AS items,
        count(emerging_rows.category_slug)::INTEGER AS item_count
      FROM emerging_rows
      RIGHT JOIN config ON TRUE
), top_markdown AS (
    SELECT COALESCE(string_agg(
        format(
            E'### %s. %s\n\n- Opportunity Score: %s/10\n- Virality Score: %s/10\n- Monetization Score: %s/10\n- Consistency Score: %s/10\n- Amostra: %s %s\n- Mediana de views: %s\n- Outlier rate: %s\n- Tendência: %s',
            top_rows.display_rank,
            initcap(replace(top_rows.category_slug, '_', ' ')),
            round(top_rows.opportunity_score, 2),
            round(top_rows.median_virality, 2),
            round(top_rows.median_monetization, 2),
            round(top_rows.consistency_score, 2),
            top_rows.sample_size,
            CASE WHEN top_rows.sample_size = 1 THEN 'vídeo' ELSE 'vídeos' END,
            COALESCE(round(top_rows.median_views, 0)::TEXT, 'indisponível'),
            COALESCE(round(top_rows.outlier_rate * 100, 2)::TEXT || '%', 'indisponível'),
            top_rows.trend_direction
        ) || CASE
            WHEN top_rows.recommendation_id IS NULL THEN E'\n\n_Recomendação estruturada ainda não disponível para este contexto._'
            ELSE format(
                E'\n\n**Recomendação (%s%s)**\n\n%s\n\n**Formatos sugeridos**\n%s\n\n**Hooks sugeridos**\n%s\n\n**Riscos**\n%s\n\n**Observações de monetização**\n%s',
                top_rows.used_prompt_version,
                CASE WHEN top_rows.used_prompt_version = config.recommendation_prompt_version THEN '' ELSE ', histórico' END,
                regexp_replace(top_rows.recommendation_summary, E'[\r\n]+', ' ', 'g'),
                COALESCE((SELECT string_agg('- ' || regexp_replace(item, E'[\r\n]+', ' ', 'g'), E'\n') FROM unnest(top_rows.recommended_formats) item), '- Não disponível'),
                COALESCE((SELECT string_agg('- ' || regexp_replace(item, E'[\r\n]+', ' ', 'g'), E'\n') FROM unnest(top_rows.recommended_hooks) item), '- Não disponível'),
                COALESCE((SELECT string_agg('- ' || regexp_replace(item, E'[\r\n]+', ' ', 'g'), E'\n') FROM unnest(top_rows.recommendation_risks) item), '- Não disponível'),
                COALESCE((SELECT string_agg('- ' || regexp_replace(item, E'[\r\n]+', ' ', 'g'), E'\n') FROM unnest(top_rows.monetization_notes) item), '- Não disponível')
            )
        END,
        E'\n\n'
        ORDER BY top_rows.display_rank
    ) FILTER (WHERE top_rows.category_slug IS NOT NULL), '_Nenhuma categoria com Opportunity Score está disponível neste contexto._') AS body
      FROM config
      LEFT JOIN top_rows ON TRUE
), risky_markdown AS (
    SELECT COALESCE(string_agg(
        format(
            E'### %s. %s\n\n- Virality Score: %s/10\n- Monetization Score: %s/10\n- Diferença de risco: %s pontos\n- Amostra: %s %s\n- Outlier rate: %s',
            risky_rows.display_rank,
            initcap(replace(risky_rows.category_slug, '_', ' ')),
            round(risky_rows.median_virality, 2),
            round(risky_rows.median_monetization, 2),
            risky_rows.risk_gap,
            risky_rows.sample_size,
            CASE WHEN risky_rows.sample_size = 1 THEN 'vídeo' ELSE 'vídeos' END,
            COALESCE(round(risky_rows.outlier_rate * 100, 2)::TEXT || '%', 'indisponível')
        ),
        E'\n\n'
        ORDER BY risky_rows.display_rank
    ) FILTER (WHERE risky_rows.category_slug IS NOT NULL), '_Nenhuma categoria atingiu simultaneamente os limites configurados de alta viralidade e baixa monetização._') AS body
      FROM config
      LEFT JOIN risky_rows ON TRUE
), emerging_markdown AS (
    SELECT COALESCE(string_agg(
        format(
            E'### %s. %s\n\n- Direção: rising\n- Variação da mediana de Virality Score: %s%%\n- Amostra atual: %s %s\n- Amostra anterior: %s %s\n- Opportunity Score: %s/10',
            emerging_rows.display_rank,
            initcap(replace(emerging_rows.category_slug, '_', ' ')),
            COALESCE(round(emerging_rows.trend_change * 100, 2)::TEXT, 'indisponível'),
            emerging_rows.sample_size,
            CASE WHEN emerging_rows.sample_size = 1 THEN 'vídeo' ELSE 'vídeos' END,
            emerging_rows.previous_sample_size,
            CASE WHEN emerging_rows.previous_sample_size = 1 THEN 'vídeo' ELSE 'vídeos' END,
            round(emerging_rows.opportunity_score, 2)
        ),
        E'\n\n'
        ORDER BY emerging_rows.display_rank
    ) FILTER (WHERE emerging_rows.category_slug IS NOT NULL), '_Nenhuma tendência emergente possui amostra suficiente no período atual._') AS body
      FROM config
      LEFT JOIN emerging_rows ON TRUE
), source_payload AS (
    SELECT jsonb_build_object(
        'schema_version', '1.0',
        'title', 'TrendLens — Relatório Semanal',
        'report_version', config.report_version,
        'period', jsonb_build_object(
            'start', bounds.period_start,
            'end', bounds.period_end,
            'timezone', config.report_timezone
        ),
        'context', jsonb_build_object(
            'platform', selected_context.platform,
            'region', selected_context.region,
            'language', selected_context.language,
            'requested_language', selected_context.requested_language
        ),
        'coverage', jsonb_build_object(
            'videos_analyzed', coverage.videos_analyzed,
            'categories_analyzed', coverage.categories_analyzed,
            'categories_with_opportunity', coverage.categories_with_opportunity,
            'recommendations_available', coverage.recommendations_available,
            'current_prompt_recommendations', coverage.current_prompt_recommendations
        ),
        'source_versions', jsonb_build_object(
            'trend', config.trend_version,
            'opportunity', config.opportunity_version,
            'recommendation_prompt', config.recommendation_prompt_version
        ),
        'top_opportunities', top_section.items,
        'viral_but_risky', risky_section.items,
        'emerging_trends', emerging_section.items,
        'methodology', jsonb_build_object(
            'viral_but_risky', jsonb_build_object(
                'minimum_virality_score', config.virality_risk_min,
                'maximum_monetization_score', config.monetization_risk_max
            ),
            'quantitative_source', 'postgresql',
            'recommendation_policy', 'patterns_not_individual_videos'
        ),
        'notices', jsonb_build_array(
            'Todos os valores quantitativos foram calculados no PostgreSQL.',
            'Scores são índices heurísticos relativos à amostra e não garantem viralização ou receita.',
            'Tendências rising exigem amostra mínima nas janelas atual e anterior.'
        )
    ) AS value
      FROM config
      CROSS JOIN selected_context
      CROSS JOIN bounds
      CROSS JOIN coverage
      CROSS JOIN top_section
      CROSS JOIN risky_section
      CROSS JOIN emerging_section
), rendered AS (
    SELECT
        source_payload.value || jsonb_build_object('generated_at', p_generated_at) AS report_json,
        format(
            E'# TrendLens — Relatório Semanal\n\n_Gerado em %s (%s)_\n\n## Escopo\n\n- Período: %s → %s\n- Plataforma: %s\n- Região: %s\n- Idioma: %s\n- Vídeos analisados: %s\n- Categorias analisadas: %s\n- Recomendações disponíveis: %s (%s no prompt atual)\n\n## Top Opportunities\n\n%s\n\n## Viral but Risky\n\n%s\n\n## Tendências emergentes\n\n%s\n\n## Notas metodológicas\n\n- Todos os valores quantitativos foram calculados no PostgreSQL.\n- Scores são índices heurísticos relativos à amostra e não garantem viralização ou receita.\n- Recomendações descrevem padrões e não vídeos individuais.\n\n_Versão do relatório: %s_',
            to_char(timezone(config.report_timezone, p_generated_at), 'DD/MM/YYYY HH24:MI'),
            config.report_timezone,
            to_char(timezone(config.report_timezone, bounds.period_start), 'DD/MM/YYYY HH24:MI'),
            to_char(timezone(config.report_timezone, bounds.period_end), 'DD/MM/YYYY HH24:MI'),
            selected_context.platform,
            selected_context.region,
            selected_context.language,
            coverage.videos_analyzed,
            coverage.categories_analyzed,
            coverage.recommendations_available,
            coverage.current_prompt_recommendations,
            top_markdown.body,
            risky_markdown.body,
            emerging_markdown.body,
            config.report_version
        ) AS report_markdown,
        md5(source_payload.value::TEXT) AS source_hash
      FROM config
      CROSS JOIN selected_context
      CROSS JOIN bounds
      CROSS JOIN coverage
      CROSS JOIN top_markdown
      CROSS JOIN risky_markdown
      CROSS JOIN emerging_markdown
      CROSS JOIN source_payload
)
SELECT
    bounds.period_start,
    bounds.period_end,
    selected_context.platform,
    selected_context.region,
    selected_context.language,
    p_generated_at,
    config.report_version,
    config.trend_version,
    config.opportunity_version,
    config.recommendation_prompt_version,
    coverage.videos_analyzed,
    coverage.categories_analyzed,
    top_section.item_count,
    risky_section.item_count,
    emerging_section.item_count,
    rendered.report_json,
    rendered.report_markdown,
    rendered.source_hash
  FROM config
  CROSS JOIN selected_context
  CROSS JOIN bounds
  CROSS JOIN coverage
  CROSS JOIN top_section
  CROSS JOIN risky_section
  CROSS JOIN emerging_section
  CROSS JOIN rendered;
$$;

COMMIT;
