BEGIN;

INSERT INTO settings (key, value, description)
VALUES
    ('OBSERVABILITY_PERIOD', '"24 hours"'::JSONB, 'Janela fechada usada pelos relatórios de observabilidade.'),
    ('OBSERVABILITY_VERSION', '"v1"'::JSONB, 'Versão do contrato JSON de observabilidade.'),
    ('OBSERVABILITY_STALE_RUN_MINUTES', '120'::JSONB, 'Tempo máximo, em minutos, para uma execução permanecer running.'),
    ('OBSERVABILITY_HIGH_VIRALITY_THRESHOLD', '7'::JSONB, 'Virality Score mínimo para contabilizar vídeos de alta viralidade.'),
    ('OBSERVABILITY_HIGH_OPPORTUNITY_THRESHOLD', '7'::JSONB, 'Opportunity Score mínimo para destacar categorias.'),
    ('OBSERVABILITY_ERROR_LIMIT', '20'::JSONB, 'Quantidade máxima de eventos recentes incluídos no relatório.'),
    ('OBSERVABILITY_TIMEZONE', '"America/Sao_Paulo"'::JSONB, 'Fuso horário de referência da observabilidade.')
ON CONFLICT (key) DO UPDATE
SET description = EXCLUDED.description;

CREATE TABLE IF NOT EXISTS pipeline_observability_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    observability_version TEXT NOT NULL,
    overall_status TEXT NOT NULL,
    workflow_count INTEGER NOT NULL,
    run_count INTEGER NOT NULL,
    error_count INTEGER NOT NULL,
    retry_count INTEGER NOT NULL,
    report_json JSONB NOT NULL,
    source_hash TEXT NOT NULL,
    CONSTRAINT pipeline_observability_period_check
        CHECK (period_end > period_start),
    CONSTRAINT pipeline_observability_version_check
        CHECK (length(btrim(observability_version)) > 0),
    CONSTRAINT pipeline_observability_status_check
        CHECK (overall_status IN ('healthy', 'degraded', 'critical')),
    CONSTRAINT pipeline_observability_counts_check
        CHECK (
            workflow_count >= 0
            AND run_count >= 0
            AND error_count >= 0
            AND retry_count >= 0
        ),
    CONSTRAINT pipeline_observability_json_check
        CHECK (
            jsonb_typeof(report_json) = 'object'
            AND report_json ? 'summary'
            AND report_json ? 'pipeline_metrics'
            AND report_json ? 'workflow_health'
            AND report_json ? 'recent_errors'
        ),
    CONSTRAINT pipeline_observability_source_hash_check
        CHECK (source_hash ~ '^[a-f0-9]{32}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS pipeline_observability_source_idx
    ON pipeline_observability_reports (
        period_start,
        period_end,
        observability_version,
        source_hash
    );

CREATE INDEX IF NOT EXISTS pipeline_observability_generated_idx
    ON pipeline_observability_reports (generated_at DESC, overall_status);

CREATE INDEX IF NOT EXISTS pipeline_runs_started_at_idx
    ON pipeline_runs (started_at DESC);

CREATE INDEX IF NOT EXISTS pipeline_errors_occurred_at_idx
    ON pipeline_errors (occurred_at DESC);

CREATE OR REPLACE FUNCTION build_pipeline_observability(
    p_generated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)
RETURNS TABLE (
    period_start TIMESTAMPTZ,
    period_end TIMESTAMPTZ,
    generated_at TIMESTAMPTZ,
    observability_version TEXT,
    overall_status TEXT,
    workflow_count INTEGER,
    run_count INTEGER,
    error_count INTEGER,
    retry_count INTEGER,
    report_json JSONB,
    source_hash TEXT
)
LANGUAGE sql
STABLE
AS $$
WITH config AS (
    SELECT
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'OBSERVABILITY_VERSION'), ''), 'v1') AS observability_version,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'OBSERVABILITY_TIMEZONE'), ''), 'America/Sao_Paulo') AS report_timezone,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'OBSERVABILITY_PERIOD'), '')::INTERVAL, INTERVAL '24 hours') AS report_period,
        GREATEST(1, COALESCE((SELECT (value #>> '{}')::INTEGER FROM settings WHERE key = 'OBSERVABILITY_STALE_RUN_MINUTES'), 120)) AS stale_run_minutes,
        GREATEST(0::NUMERIC, LEAST(10::NUMERIC, COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'OBSERVABILITY_HIGH_VIRALITY_THRESHOLD'), 7))) AS high_virality_threshold,
        GREATEST(0::NUMERIC, LEAST(10::NUMERIC, COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'OBSERVABILITY_HIGH_OPPORTUNITY_THRESHOLD'), 7))) AS high_opportunity_threshold,
        GREATEST(1, LEAST(100, COALESCE((SELECT (value #>> '{}')::INTEGER FROM settings WHERE key = 'OBSERVABILITY_ERROR_LIMIT'), 20))) AS error_limit,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'METRICS_CALCULATION_VERSION'), ''), 'v1') AS metrics_version,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'TREND_CALCULATION_VERSION'), ''), 'v1') AS trend_version,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'OPPORTUNITY_CALCULATION_VERSION'), ''), 'v1') AS opportunity_version
), bounds AS (
    SELECT
        date_trunc('hour', p_generated_at) - config.report_period AS period_start,
        date_trunc('hour', p_generated_at) AS period_end
      FROM config
), expected_workflows AS (
    SELECT *
      FROM (VALUES
        (1, '01 - TrendLens - YouTube Data Collector', 'collection'),
        (2, '02 - TrendLens - Video Snapshot Tracker', 'snapshots'),
        (3, '03 - TrendLens - AI Content Classifier', 'classification'),
        (4, '04 - TrendLens - Metrics Engine & Virality Score', 'metrics'),
        (5, '05 - TrendLens - Trend Engine', 'trends'),
        (6, '06 - TrendLens - Monetization Engine', 'monetization'),
        (7, '07 - TrendLens - Opportunity Engine', 'opportunities'),
        (8, '08 - TrendLens - Recommendation AI', 'recommendations'),
        (9, '09 - TrendLens - Report', 'reporting')
      ) AS workflow(sort_order, workflow, stage)
), period_runs AS MATERIALIZED (
    SELECT run.*
      FROM pipeline_runs run
      CROSS JOIN bounds
     WHERE run.started_at >= bounds.period_start
       AND run.started_at < bounds.period_end
       AND run.workflow IN (SELECT workflow FROM expected_workflows)
), period_errors AS MATERIALIZED (
    SELECT error.*
      FROM pipeline_errors error
      CROSS JOIN bounds
     WHERE error.occurred_at >= bounds.period_start
       AND error.occurred_at < bounds.period_end
       AND error.workflow IN (SELECT workflow FROM expected_workflows)
), run_stats AS (
    SELECT
        expected.sort_order,
        expected.workflow,
        expected.stage,
        count(run.id)::INTEGER AS run_count,
        count(run.id) FILTER (WHERE run.status = 'success')::INTEGER AS success_count,
        count(run.id) FILTER (WHERE run.status = 'partial')::INTEGER AS partial_count,
        count(run.id) FILTER (WHERE run.status = 'failed')::INTEGER AS failed_count,
        count(run.id) FILTER (WHERE run.status = 'running')::INTEGER AS running_count,
        COALESCE(sum(run.items_received), 0)::BIGINT AS items_received,
        COALESCE(sum(run.items_processed), 0)::BIGINT AS items_processed,
        COALESCE(sum(run.items_skipped), 0)::BIGINT AS items_skipped,
        COALESCE(sum(run.items_failed), 0)::BIGINT AS items_failed,
        COALESCE(sum(run.api_calls), 0)::BIGINT AS api_calls,
        COALESCE(sum(run.quota_units_estimated), 0)::BIGINT AS quota_units_estimated,
        round(avg(run.duration_seconds) FILTER (WHERE run.duration_seconds IS NOT NULL), 3) AS average_duration_seconds,
        round(percentile_cont(0.95) WITHIN GROUP (ORDER BY run.duration_seconds) FILTER (WHERE run.duration_seconds IS NOT NULL)::NUMERIC, 3) AS p95_duration_seconds
      FROM expected_workflows expected
      LEFT JOIN period_runs run ON run.workflow = expected.workflow
     GROUP BY expected.sort_order, expected.workflow, expected.stage
), error_stats AS (
    SELECT
        expected.workflow,
        count(error.id)::INTEGER AS error_events,
        COALESCE(sum(error.retry_count), 0)::INTEGER AS retry_count
      FROM expected_workflows expected
      LEFT JOIN period_errors error ON error.workflow = expected.workflow
     GROUP BY expected.workflow
), stale_stats AS (
    SELECT
        expected.workflow,
        count(run.id)::INTEGER AS stale_running_count
      FROM expected_workflows expected
      CROSS JOIN config
      CROSS JOIN bounds
      LEFT JOIN pipeline_runs run
        ON run.workflow = expected.workflow
       AND run.status = 'running'
       AND run.started_at < bounds.period_end - make_interval(mins => config.stale_run_minutes)
     GROUP BY expected.workflow
), latest_runs AS (
    SELECT
        expected.workflow,
        latest.id,
        latest.status,
        latest.started_at,
        latest.finished_at,
        latest.duration_seconds
      FROM expected_workflows expected
      CROSS JOIN bounds
      LEFT JOIN LATERAL (
          SELECT run.id, run.status, run.started_at, run.finished_at, run.duration_seconds
            FROM pipeline_runs run
           WHERE run.workflow = expected.workflow
             AND run.started_at < bounds.period_end
           ORDER BY run.started_at DESC, run.id DESC
           LIMIT 1
      ) latest ON TRUE
), workflow_rows AS (
    SELECT
        stats.*,
        errors.error_events,
        errors.retry_count,
        stale.stale_running_count,
        latest.id AS latest_run_id,
        latest.status AS latest_status,
        latest.started_at AS latest_started_at,
        latest.finished_at AS latest_finished_at,
        latest.duration_seconds AS latest_duration_seconds,
        CASE
            WHEN stale.stale_running_count > 0 OR stats.failed_count > 0 THEN 'critical'
            WHEN stats.partial_count > 0 OR errors.error_events > 0 THEN 'degraded'
            WHEN stats.run_count = 0 THEN 'unknown'
            ELSE 'healthy'
        END AS health_status
      FROM run_stats stats
      JOIN error_stats errors USING (workflow)
      JOIN stale_stats stale USING (workflow)
      JOIN latest_runs latest USING (workflow)
), workflow_section AS (
    SELECT jsonb_agg(
        jsonb_build_object(
            'workflow', workflow,
            'stage', stage,
            'health_status', health_status,
            'runs', jsonb_build_object(
                'total', run_count,
                'success', success_count,
                'partial', partial_count,
                'failed', failed_count,
                'running', running_count,
                'stale_running', stale_running_count
            ),
            'counters', jsonb_build_object(
                'items_received', items_received,
                'items_processed', items_processed,
                'items_skipped', items_skipped,
                'items_failed', items_failed,
                'api_calls', api_calls,
                'quota_units_estimated', quota_units_estimated,
                'error_events', error_events,
                'retries', retry_count
            ),
            'duration_seconds', jsonb_build_object(
                'average', average_duration_seconds,
                'p95', p95_duration_seconds
            ),
            'latest_run', CASE
                WHEN latest_run_id IS NULL THEN NULL
                ELSE jsonb_build_object(
                    'id', latest_run_id,
                    'status', latest_status,
                    'started_at', latest_started_at,
                    'finished_at', latest_finished_at,
                    'duration_seconds', latest_duration_seconds
                )
            END
        ) ORDER BY sort_order
    ) AS items
      FROM workflow_rows
), summary AS (
    SELECT
        count(*)::INTEGER AS workflow_count,
        COALESCE(sum(run_count), 0)::INTEGER AS run_count,
        COALESCE(sum(success_count), 0)::INTEGER AS success_count,
        COALESCE(sum(partial_count), 0)::INTEGER AS partial_count,
        COALESCE(sum(failed_count), 0)::INTEGER AS failed_count,
        COALESCE(sum(running_count), 0)::INTEGER AS running_count,
        COALESCE(sum(items_failed), 0)::BIGINT AS items_failed,
        COALESCE(sum(error_events), 0)::INTEGER AS error_count,
        COALESCE(sum(retry_count), 0)::INTEGER AS retry_count,
        count(*) FILTER (WHERE health_status = 'healthy')::INTEGER AS healthy_workflows,
        count(*) FILTER (WHERE health_status = 'degraded')::INTEGER AS degraded_workflows,
        count(*) FILTER (WHERE health_status = 'critical')::INTEGER AS critical_workflows,
        count(*) FILTER (WHERE health_status = 'unknown')::INTEGER AS unknown_workflows,
        CASE
            WHEN count(*) FILTER (WHERE health_status = 'critical') > 0 THEN 'critical'
            WHEN count(*) FILTER (WHERE health_status = 'degraded') > 0 THEN 'degraded'
            ELSE 'healthy'
        END AS overall_status
      FROM workflow_rows
), scalar_metrics AS (
    SELECT
        COALESCE(sum(run.items_processed) FILTER (WHERE run.workflow = '01 - TrendLens - YouTube Data Collector'), 0)::BIGINT AS videos_collected,
        COALESCE(sum(CASE WHEN run.workflow = '01 - TrendLens - YouTube Data Collector' THEN COALESCE((run.metadata ->> 'new_videos')::BIGINT, 0) ELSE 0 END), 0)::BIGINT AS new_videos,
        COALESCE(sum(CASE WHEN run.workflow = '01 - TrendLens - YouTube Data Collector' THEN COALESCE((run.metadata ->> 'duplicate_videos')::BIGINT, 0) ELSE 0 END), 0)::BIGINT AS duplicate_videos,
        COALESCE(sum(CASE WHEN run.workflow IN ('01 - TrendLens - YouTube Data Collector', '02 - TrendLens - Video Snapshot Tracker') THEN COALESCE((run.metadata ->> 'snapshots_collected')::BIGINT, 0) ELSE 0 END), 0)::BIGINT AS snapshots_collected,
        COALESCE(sum(run.items_processed) FILTER (WHERE run.workflow = '03 - TrendLens - AI Content Classifier'), 0)::BIGINT AS ai_classifications,
        COALESCE(sum(run.items_failed) FILTER (WHERE run.workflow = '03 - TrendLens - AI Content Classifier'), 0)::BIGINT AS classification_errors,
        round((
            sum(run.duration_seconds) FILTER (
                WHERE run.workflow = '03 - TrendLens - AI Content Classifier'
                  AND run.finished_at IS NOT NULL
            ) / NULLIF(sum(run.items_processed + run.items_failed) FILTER (
                WHERE run.workflow = '03 - TrendLens - AI Content Classifier'
                  AND run.finished_at IS NOT NULL
            ), 0)
        )::NUMERIC, 3) AS average_classification_latency_seconds,
        (SELECT count(*)::INTEGER FROM period_errors error WHERE error.error_type ~ '^(youtube|ai)_') AS api_errors,
        (SELECT COALESCE(sum(error.retry_count), 0)::INTEGER FROM period_errors error) AS retries,
        COALESCE(sum(run.items_failed), 0)::BIGINT AS items_with_error
      FROM period_runs run
), videos_by_category AS (
    SELECT COALESCE(jsonb_agg(
        jsonb_build_object(
            'category', category,
            'videos', videos
        ) ORDER BY videos DESC, category
    ), '[]'::JSONB) AS items
      FROM (
        SELECT COALESCE(category.slug, 'uncategorized') AS category, count(*)::INTEGER AS videos
          FROM video_classifications classification
          LEFT JOIN categories category ON category.id = classification.category_id
          CROSS JOIN bounds
         WHERE classification.classified_at < bounds.period_end
         GROUP BY COALESCE(category.slug, 'uncategorized')
      ) grouped
), high_virality AS (
    SELECT
        count(*)::INTEGER AS total,
        COALESCE(jsonb_agg(
            jsonb_build_object(
                'video_id', ranked.video_id,
                'external_id', ranked.external_id,
                'virality_score', ranked.virality_score,
                'calculated_at', ranked.calculated_at
            ) ORDER BY ranked.virality_score DESC, ranked.video_id
        ) FILTER (WHERE ranked.display_order <= 10), '[]'::JSONB) AS items
      FROM (
        SELECT
            latest.video_id,
            latest.external_id,
            latest.virality_score,
            latest.calculated_at,
            row_number() OVER (ORDER BY latest.virality_score DESC, latest.video_id) AS display_order
          FROM (
            SELECT DISTINCT ON (metric.video_id)
                metric.video_id,
                video.external_id,
                metric.virality_score,
                metric.calculated_at
              FROM video_metrics metric
              JOIN videos video ON video.id = metric.video_id
              CROSS JOIN config
              CROSS JOIN bounds
             WHERE metric.calculation_version = config.metrics_version
               AND metric.calculated_at < bounds.period_end
             ORDER BY metric.video_id, metric.calculated_at DESC, metric.id DESC
          ) latest
          CROSS JOIN config
         WHERE latest.virality_score >= config.high_virality_threshold
      ) ranked
), latest_opportunity_period AS (
    SELECT max(statistic.period_end) AS period_end
      FROM category_statistics statistic
      CROSS JOIN config
      CROSS JOIN bounds
     WHERE statistic.dimension_type = 'category'
       AND statistic.calculation_version = config.trend_version
       AND statistic.opportunity_calculation_version = config.opportunity_version
       AND statistic.opportunity_score IS NOT NULL
       AND statistic.period_end < bounds.period_end
), high_opportunities AS (
    SELECT
        count(*)::INTEGER AS total,
        COALESCE(jsonb_agg(
            jsonb_build_object(
                'category', statistic.category_slug,
                'opportunity_score', statistic.opportunity_score,
                'opportunity_rank', statistic.opportunity_rank,
                'sample_size', statistic.sample_size,
                'period_end', statistic.period_end
            ) ORDER BY statistic.opportunity_score DESC, statistic.category_slug
        ) FILTER (WHERE statistic.category_slug IS NOT NULL), '[]'::JSONB) AS items
      FROM category_statistics statistic
      CROSS JOIN config
      CROSS JOIN latest_opportunity_period latest
     WHERE statistic.dimension_type = 'category'
       AND statistic.calculation_version = config.trend_version
       AND statistic.opportunity_calculation_version = config.opportunity_version
       AND statistic.period_end = latest.period_end
       AND statistic.opportunity_score >= config.high_opportunity_threshold
), recent_errors AS (
    SELECT COALESCE(jsonb_agg(
        jsonb_build_object(
            'id', recent.id,
            'pipeline_run_id', recent.pipeline_run_id,
            'workflow', recent.workflow,
            'node', recent.node,
            'occurred_at', recent.occurred_at,
            'error_type', recent.error_type,
            'external_id', recent.external_id,
            'retry_count', recent.retry_count
        ) ORDER BY recent.occurred_at DESC, recent.id DESC
    ), '[]'::JSONB) AS items
      FROM (
        SELECT
            error.*,
            row_number() OVER (ORDER BY error.occurred_at DESC, error.id DESC) AS error_order
          FROM period_errors error
      ) recent
      CROSS JOIN config
     WHERE recent.error_order <= config.error_limit
), source_payload AS (
    SELECT jsonb_build_object(
        'schema_version', '1.0',
        'observability_version', config.observability_version,
        'period', jsonb_build_object(
            'start', bounds.period_start,
            'end', bounds.period_end,
            'timezone', config.report_timezone,
            'closed_window', true
        ),
        'status', summary.overall_status,
        'summary', jsonb_build_object(
            'workflows', summary.workflow_count,
            'runs', summary.run_count,
            'success', summary.success_count,
            'partial', summary.partial_count,
            'failed', summary.failed_count,
            'running', summary.running_count,
            'items_with_error', summary.items_failed,
            'error_events', summary.error_count,
            'retries', summary.retry_count,
            'healthy_workflows', summary.healthy_workflows,
            'degraded_workflows', summary.degraded_workflows,
            'critical_workflows', summary.critical_workflows,
            'unknown_workflows', summary.unknown_workflows
        ),
        'pipeline_metrics', jsonb_build_object(
            'videos_collected', scalar_metrics.videos_collected,
            'new_videos', scalar_metrics.new_videos,
            'duplicate_videos', scalar_metrics.duplicate_videos,
            'snapshots_collected', scalar_metrics.snapshots_collected,
            'ai_classifications', scalar_metrics.ai_classifications,
            'classification_errors', scalar_metrics.classification_errors,
            'average_classification_latency_seconds', scalar_metrics.average_classification_latency_seconds,
            'api_errors', scalar_metrics.api_errors,
            'retries', scalar_metrics.retries,
            'items_with_error', scalar_metrics.items_with_error,
            'videos_by_category', videos_by_category.items,
            'high_virality_videos', jsonb_build_object(
                'threshold', config.high_virality_threshold,
                'total', high_virality.total,
                'top_items', high_virality.items
            ),
            'high_opportunity_categories', jsonb_build_object(
                'threshold', config.high_opportunity_threshold,
                'total', high_opportunities.total,
                'items', high_opportunities.items
            )
        ),
        'workflow_health', workflow_section.items,
        'recent_errors', recent_errors.items,
        'methodology', jsonb_build_object(
            'run_window', '[start,end)',
            'classification_latency', 'sum_duration_divided_by_processed_plus_failed',
            'retry_scope', 'retries_recorded_on_terminal_errors',
            'error_payload_policy', 'messages_and_metadata_omitted'
        ),
        'notices', jsonb_build_array(
            'A janela termina no início da hora corrente para produzir snapshots idempotentes.',
            'Retries bem-sucedidos dentro de um node não são expostos pelo n8n e não entram no contador.',
            'Eventos recentes omitem error_message e metadata para não expor dados sensíveis.'
        )
    ) AS value
      FROM config
      CROSS JOIN bounds
      CROSS JOIN summary
      CROSS JOIN scalar_metrics
      CROSS JOIN videos_by_category
      CROSS JOIN high_virality
      CROSS JOIN high_opportunities
      CROSS JOIN workflow_section
      CROSS JOIN recent_errors
), rendered AS (
    SELECT
        source_payload.value || jsonb_build_object(
            'generated_at', p_generated_at,
            'source_hash', md5(source_payload.value::TEXT)
        ) AS report_json,
        md5(source_payload.value::TEXT) AS source_hash
      FROM source_payload
)
SELECT
    bounds.period_start,
    bounds.period_end,
    p_generated_at,
    config.observability_version,
    summary.overall_status,
    summary.workflow_count,
    summary.run_count,
    summary.error_count,
    summary.retry_count,
    rendered.report_json,
    rendered.source_hash
  FROM config
  CROSS JOIN bounds
  CROSS JOIN summary
  CROSS JOIN rendered;
$$;

COMMIT;
