BEGIN;

INSERT INTO settings (key, value, description)
VALUES
    ('VALIDATION_PERIOD', '"7 days"'::JSONB, 'Janela observacional usada pela validação da Fase 12.'),
    ('VALIDATION_VERSION', '"v1"'::JSONB, 'Versão do contrato JSON de validação.'),
    ('VALIDATION_MIN_OBSERVATION_DAYS', '3'::JSONB, 'Quantidade mínima de dias entre o primeiro e o último snapshot da janela.'),
    ('VALIDATION_MIN_CATEGORY_SAMPLE_SIZE', '30'::JSONB, 'Amostra mínima por categoria para revisar pesos.'),
    ('VALIDATION_MIN_CLASSIFIER_REVIEWS', '30'::JSONB, 'Quantidade mínima de revisões humanas concluídas do classificador.'),
    ('VALIDATION_CLASSIFIER_CONFIDENCE_FLOOR', '0.65'::JSONB, 'Confiança abaixo da qual uma classificação recebe atenção adicional.'),
    ('VALIDATION_SCORE_TAIL_THRESHOLD', '0.10'::JSONB, 'Taxa máxima esperada em cada cauda extrema dos scores.'),
    ('VALIDATION_SNAPSHOT_CADENCE_TOLERANCE', '1.50'::JSONB, 'Multiplicador tolerado sobre o intervalo esperado entre snapshots.')
ON CONFLICT (key) DO UPDATE
SET description = EXCLUDED.description;

CREATE TABLE IF NOT EXISTS classification_validation_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id BIGINT NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    prompt_version TEXT NOT NULL,
    reviewer TEXT NOT NULL,
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    category_correct BOOLEAN NOT NULL,
    topic_correct BOOLEAN NOT NULL,
    content_type_correct BOOLEAN NOT NULL,
    format_correct BOOLEAN NOT NULL,
    hook_type_correct BOOLEAN NOT NULL,
    source_type_correct BOOLEAN NOT NULL,
    presentation_style_correct BOOLEAN NOT NULL,
    originality_reasonable BOOLEAN NOT NULL,
    copyright_risk_reasonable BOOLEAN NOT NULL,
    reused_content_risk_reasonable BOOLEAN NOT NULL,
    corrected_values JSONB NOT NULL DEFAULT '{}'::JSONB,
    notes TEXT,
    CONSTRAINT classification_validation_review_identity_unique
        UNIQUE (video_id, prompt_version, reviewer),
    CONSTRAINT classification_validation_prompt_check
        CHECK (length(btrim(prompt_version)) > 0),
    CONSTRAINT classification_validation_reviewer_check
        CHECK (length(btrim(reviewer)) > 0),
    CONSTRAINT classification_validation_corrected_values_check
        CHECK (jsonb_typeof(corrected_values) = 'object'),
    CONSTRAINT classification_validation_notes_check
        CHECK (notes IS NULL OR length(notes) <= 4000)
);

CREATE INDEX IF NOT EXISTS classification_validation_reviewed_idx
    ON classification_validation_reviews (reviewed_at DESC, prompt_version);

CREATE TABLE IF NOT EXISTS pipeline_validation_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validation_version TEXT NOT NULL,
    overall_status TEXT NOT NULL,
    sample_size INTEGER NOT NULL,
    reviewed_classifications INTEGER NOT NULL,
    report_json JSONB NOT NULL,
    source_hash TEXT NOT NULL,
    CONSTRAINT pipeline_validation_period_check
        CHECK (period_end > period_start),
    CONSTRAINT pipeline_validation_version_check
        CHECK (length(btrim(validation_version)) > 0),
    CONSTRAINT pipeline_validation_status_check
        CHECK (overall_status IN ('insufficient_data', 'needs_attention', 'ready_for_weight_review')),
    CONSTRAINT pipeline_validation_counts_check
        CHECK (sample_size >= 0 AND reviewed_classifications >= 0),
    CONSTRAINT pipeline_validation_json_check
        CHECK (
            jsonb_typeof(report_json) = 'object'
            AND report_json ? 'data_coverage'
            AND report_json ? 'snapshot_quality'
            AND report_json ? 'classifier_review'
            AND report_json ? 'score_diagnostics'
            AND report_json ? 'category_comparison'
            AND report_json ? 'weight_review'
        ),
    CONSTRAINT pipeline_validation_source_hash_check
        CHECK (source_hash ~ '^[a-f0-9]{32}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS pipeline_validation_source_idx
    ON pipeline_validation_reports (
        period_start,
        period_end,
        validation_version,
        source_hash
    );

CREATE INDEX IF NOT EXISTS pipeline_validation_generated_idx
    ON pipeline_validation_reports (generated_at DESC, overall_status);

CREATE OR REPLACE FUNCTION select_classification_review_candidates(
    p_limit INTEGER DEFAULT 30,
    p_seed TEXT DEFAULT 'phase12-v1'
)
RETURNS TABLE (
    video_id BIGINT,
    external_id TEXT,
    url TEXT,
    title TEXT,
    description TEXT,
    published_at TIMESTAMPTZ,
    category_slug TEXT,
    topic TEXT,
    content_type TEXT,
    format TEXT,
    hook_type TEXT,
    source_type TEXT,
    presentation_style TEXT,
    originality_score NUMERIC,
    copyright_risk NUMERIC,
    reused_content_risk NUMERIC,
    ai_confidence NUMERIC,
    confidence_bucket TEXT,
    prompt_version TEXT,
    classification_model TEXT,
    sample_groups TEXT[]
)
LANGUAGE sql
STABLE
AS $$
WITH candidates AS (
    SELECT
        video.id AS video_id,
        video.external_id,
        video.url,
        video.title,
        video.description,
        video.published_at,
        category.slug AS category_slug,
        classification.topic,
        classification.content_type,
        classification.format,
        classification.hook_type,
        classification.source_type,
        classification.presentation_style,
        classification.originality_score,
        classification.copyright_risk,
        classification.reused_content_risk,
        classification.ai_confidence,
        CASE
            WHEN classification.ai_confidence < 0.65 THEN 'low'
            WHEN classification.ai_confidence < 0.85 THEN 'medium'
            ELSE 'high'
        END AS confidence_bucket,
        classification.prompt_version,
        classification.classification_model,
        COALESCE(provenance.sample_groups, ARRAY[]::TEXT[]) AS sample_groups
      FROM video_classifications classification
      JOIN videos video ON video.id = classification.video_id
      LEFT JOIN categories category ON category.id = classification.category_id
      LEFT JOIN LATERAL (
          SELECT array_agg(DISTINCT query.sample_group ORDER BY query.sample_group) AS sample_groups
            FROM video_collection_matches match
            JOIN collection_queries query ON query.id = match.collection_query_id
           WHERE match.video_id = video.id
      ) provenance ON TRUE
     WHERE NOT EXISTS (
        SELECT 1
          FROM classification_validation_reviews review
         WHERE review.video_id = classification.video_id
           AND review.prompt_version = classification.prompt_version
     )
), stratified AS (
    SELECT
        candidates.*,
        row_number() OVER (
            PARTITION BY COALESCE(candidates.category_slug, 'uncategorized'), candidates.confidence_bucket
            ORDER BY md5(candidates.external_id || p_seed), candidates.video_id
        ) AS stratum_rank
      FROM candidates
)
SELECT
    stratified.video_id,
    stratified.external_id,
    stratified.url,
    stratified.title,
    stratified.description,
    stratified.published_at,
    stratified.category_slug,
    stratified.topic,
    stratified.content_type,
    stratified.format,
    stratified.hook_type,
    stratified.source_type,
    stratified.presentation_style,
    stratified.originality_score,
    stratified.copyright_risk,
    stratified.reused_content_risk,
    stratified.ai_confidence,
    stratified.confidence_bucket,
    stratified.prompt_version,
    stratified.classification_model,
    stratified.sample_groups
  FROM stratified
 ORDER BY
    stratified.stratum_rank,
    CASE stratified.confidence_bucket WHEN 'low' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
    COALESCE(stratified.category_slug, 'uncategorized'),
    md5(stratified.external_id || p_seed)
 LIMIT GREATEST(COALESCE(p_limit, 30), 0);
$$;

CREATE OR REPLACE FUNCTION build_phase12_validation(
    p_generated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)
RETURNS TABLE (
    period_start TIMESTAMPTZ,
    period_end TIMESTAMPTZ,
    generated_at TIMESTAMPTZ,
    validation_version TEXT,
    overall_status TEXT,
    sample_size INTEGER,
    reviewed_classifications INTEGER,
    report_json JSONB,
    source_hash TEXT
)
LANGUAGE sql
STABLE
AS $$
WITH config AS (
    SELECT
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'VALIDATION_VERSION'), ''), 'v1') AS validation_version,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'VALIDATION_PERIOD'), '')::INTERVAL, INTERVAL '7 days') AS validation_period,
        GREATEST(1, COALESCE((SELECT (value #>> '{}')::INTEGER FROM settings WHERE key = 'VALIDATION_MIN_OBSERVATION_DAYS'), 3)) AS min_observation_days,
        GREATEST(1, COALESCE((SELECT (value #>> '{}')::INTEGER FROM settings WHERE key = 'VALIDATION_MIN_CATEGORY_SAMPLE_SIZE'), 30)) AS min_category_sample,
        GREATEST(1, COALESCE((SELECT (value #>> '{}')::INTEGER FROM settings WHERE key = 'VALIDATION_MIN_CLASSIFIER_REVIEWS'), 30)) AS min_classifier_reviews,
        GREATEST(0::NUMERIC, LEAST(1::NUMERIC, COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'VALIDATION_CLASSIFIER_CONFIDENCE_FLOOR'), 0.65))) AS confidence_floor,
        GREATEST(0::NUMERIC, LEAST(1::NUMERIC, COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'VALIDATION_SCORE_TAIL_THRESHOLD'), 0.10))) AS score_tail_threshold,
        GREATEST(1::NUMERIC, COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'VALIDATION_SNAPSHOT_CADENCE_TOLERANCE'), 1.50)) AS cadence_tolerance,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'METRICS_CALCULATION_VERSION'), ''), 'v1') AS metrics_version,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'MONETIZATION_CALCULATION_VERSION'), ''), 'v1') AS monetization_version,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'TREND_CALCULATION_VERSION'), ''), 'v1') AS trend_version,
        COALESCE(NULLIF((SELECT value #>> '{}' FROM settings WHERE key = 'OPPORTUNITY_CALCULATION_VERSION'), ''), 'v1') AS opportunity_version,
        GREATEST(1, COALESCE((SELECT (value #>> '{}')::INTEGER FROM settings WHERE key = 'SNAPSHOT_RECENT_MAX_AGE_HOURS'), 24)) AS recent_max_age_hours,
        GREATEST(1, COALESCE((SELECT (value #>> '{}')::INTEGER FROM settings WHERE key = 'SNAPSHOT_INTERMEDIATE_MAX_AGE_HOURS'), 72)) AS intermediate_max_age_hours,
        GREATEST(1, COALESCE((SELECT (value #>> '{}')::INTEGER FROM settings WHERE key = 'SNAPSHOT_RECENT_INTERVAL_MINUTES'), 60)) AS recent_interval_minutes,
        GREATEST(1, COALESCE((SELECT (value #>> '{}')::INTEGER FROM settings WHERE key = 'SNAPSHOT_INTERMEDIATE_INTERVAL_MINUTES'), 360)) AS intermediate_interval_minutes,
        GREATEST(1, COALESCE((SELECT (value #>> '{}')::INTEGER FROM settings WHERE key = 'SNAPSHOT_OLDER_INTERVAL_MINUTES'), 1440)) AS older_interval_minutes,
        COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'VIRALITY_VELOCITY_WEIGHT'), 0.35) AS virality_velocity_weight,
        COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'VIRALITY_ENGAGEMENT_WEIGHT'), 0.20) AS virality_engagement_weight,
        COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'VIRALITY_OUTLIER_WEIGHT'), 0.20) AS virality_outlier_weight,
        COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'VIRALITY_VIEWS_WEIGHT'), 0.15) AS virality_views_weight,
        COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'VIRALITY_FRESHNESS_WEIGHT'), 0.10) AS virality_freshness_weight,
        COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'OPPORTUNITY_VIRALITY_WEIGHT'), 0.50) AS opportunity_virality_weight,
        COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'OPPORTUNITY_MONETIZATION_WEIGHT'), 0.35) AS opportunity_monetization_weight,
        COALESCE((SELECT (value #>> '{}')::NUMERIC FROM settings WHERE key = 'OPPORTUNITY_CONSISTENCY_WEIGHT'), 0.15) AS opportunity_consistency_weight
), bounds AS (
    SELECT
        date_trunc('hour', p_generated_at) - config.validation_period AS period_start,
        date_trunc('hour', p_generated_at) AS period_end
      FROM config
), period_videos AS MATERIALIZED (
    SELECT video.*
      FROM videos video
      CROSS JOIN bounds
     WHERE video.platform = 'youtube'
       AND video.published_at >= bounds.period_start
       AND video.published_at < bounds.period_end
), period_snapshots AS MATERIALIZED (
    SELECT snapshot.*, video.published_at
      FROM video_snapshots snapshot
      JOIN period_videos video ON video.id = snapshot.video_id
      CROSS JOIN bounds
     WHERE snapshot.collected_at < bounds.period_end
), snapshot_ordered AS (
    SELECT
        snapshot.*,
        lag(snapshot.collected_at) OVER sequence AS previous_collected_at,
        lag(snapshot.views) OVER sequence AS previous_views,
        lag(snapshot.likes) OVER sequence AS previous_likes,
        lag(snapshot.comments) OVER sequence AS previous_comments
      FROM period_snapshots snapshot
    WINDOW sequence AS (PARTITION BY snapshot.video_id ORDER BY snapshot.collected_at, snapshot.id)
), snapshot_pairs AS (
    SELECT
        ordered.*,
        CASE
            WHEN ordered.previous_collected_at - ordered.published_at <= make_interval(hours => config.recent_max_age_hours)
                THEN config.recent_interval_minutes
            WHEN ordered.previous_collected_at - ordered.published_at <= make_interval(hours => config.intermediate_max_age_hours)
                THEN config.intermediate_interval_minutes
            ELSE config.older_interval_minutes
        END AS expected_interval_minutes
      FROM snapshot_ordered ordered
      CROSS JOIN config
     WHERE ordered.previous_collected_at IS NOT NULL
), snapshot_summary AS (
    SELECT
        count(*)::INTEGER AS snapshots,
        count(DISTINCT video_id)::INTEGER AS tracked_videos,
        count(DISTINCT video_id) FILTER (WHERE snapshot_count >= 2)::INTEGER AS videos_with_follow_up,
        round(extract(epoch FROM (max(collected_at) - min(collected_at)))::NUMERIC / 86400, 3) AS observation_days
      FROM (
          SELECT period_snapshots.*, count(*) OVER (PARTITION BY video_id) AS snapshot_count
            FROM period_snapshots
      ) counted
), snapshot_anomalies AS (
    SELECT
        count(*)::INTEGER AS comparable_pairs,
        count(*) FILTER (WHERE views < previous_views)::INTEGER AS views_decreased,
        count(*) FILTER (WHERE likes IS NOT NULL AND previous_likes IS NOT NULL AND likes < previous_likes)::INTEGER AS likes_decreased,
        count(*) FILTER (WHERE comments IS NOT NULL AND previous_comments IS NOT NULL AND comments < previous_comments)::INTEGER AS comments_decreased,
        count(*) FILTER (
            WHERE extract(epoch FROM (collected_at - previous_collected_at)) / 60
                > expected_interval_minutes * config.cadence_tolerance
        )::INTEGER AS cadence_gaps
      FROM snapshot_pairs
      CROSS JOIN config
), snapshot_errors AS (
    SELECT count(*)::INTEGER AS terminal_events
      FROM pipeline_errors error
      CROSS JOIN bounds
     WHERE error.workflow = '02 - TrendLens - Video Snapshot Tracker'
       AND error.occurred_at >= bounds.period_start
       AND error.occurred_at < bounds.period_end
), provenance AS (
    SELECT
        count(DISTINCT match.video_id) FILTER (WHERE query.sample_group = 'recent')::INTEGER AS recent_videos,
        count(DISTINCT match.video_id) FILTER (WHERE query.sample_group = 'high_performance')::INTEGER AS high_performance_videos,
        count(DISTINCT match.video_id) FILTER (WHERE query.sample_group = 'recent')::NUMERIC
            / NULLIF(count(DISTINCT match.video_id), 0) AS recent_share,
        count(DISTINCT match.video_id) FILTER (WHERE query.sample_group = 'high_performance')::NUMERIC
            / NULLIF(count(DISTINCT match.video_id), 0) AS high_performance_share
      FROM video_collection_matches match
      JOIN collection_queries query ON query.id = match.collection_query_id
      JOIN period_videos video ON video.id = match.video_id
), latest_observations AS MATERIALIZED (
    SELECT
        video.id AS video_id,
        category.slug AS category_slug,
        classification.ai_confidence,
        snapshot.views,
        metric.velocity_percentile,
        metric.engagement_percentile,
        metric.outlier_percentile,
        metric.views_percentile,
        metric.freshness_score,
        metric.virality_score,
        monetization.monetization_score
      FROM period_videos video
      LEFT JOIN video_classifications classification ON classification.video_id = video.id
      LEFT JOIN categories category ON category.id = classification.category_id
      LEFT JOIN LATERAL (
          SELECT value.*
            FROM video_snapshots value
            CROSS JOIN bounds
           WHERE value.video_id = video.id
             AND value.collected_at < bounds.period_end
           ORDER BY value.collected_at DESC, value.id DESC
           LIMIT 1
      ) snapshot ON TRUE
      LEFT JOIN video_metrics metric
        ON metric.snapshot_id = snapshot.id
       AND metric.calculation_version = (SELECT metrics_version FROM config)
      LEFT JOIN video_monetization_scores monetization
        ON monetization.video_id = video.id
       AND monetization.calculation_version = (SELECT monetization_version FROM config)
), coverage AS (
    SELECT
        count(*)::INTEGER AS videos,
        count(*) FILTER (WHERE category_slug IS NOT NULL)::INTEGER AS classifications,
        count(*) FILTER (WHERE virality_score IS NOT NULL)::INTEGER AS virality_scores,
        count(*) FILTER (WHERE monetization_score IS NOT NULL)::INTEGER AS monetization_scores,
        count(DISTINCT category_slug)::INTEGER AS represented_categories
      FROM latest_observations
), review_flags AS (
    SELECT review.id, flag.dimension, flag.correct
      FROM classification_validation_reviews review
      JOIN period_videos video ON video.id = review.video_id
      CROSS JOIN LATERAL (VALUES
          ('category', review.category_correct),
          ('topic', review.topic_correct),
          ('content_type', review.content_type_correct),
          ('format', review.format_correct),
          ('hook_type', review.hook_type_correct),
          ('source_type', review.source_type_correct),
          ('presentation_style', review.presentation_style_correct),
          ('originality', review.originality_reasonable),
          ('copyright_risk', review.copyright_risk_reasonable),
          ('reused_content_risk', review.reused_content_risk_reasonable)
      ) flag(dimension, correct)
), review_by_dimension AS (
    SELECT COALESCE(jsonb_agg(
        jsonb_build_object(
            'dimension', dimension,
            'reviewed', reviewed,
            'accepted', accepted,
            'acceptance_rate', acceptance_rate
        ) ORDER BY dimension
    ), '[]'::JSONB) AS items
      FROM (
          SELECT
              dimension,
              count(*)::INTEGER AS reviewed,
              count(*) FILTER (WHERE correct)::INTEGER AS accepted,
              round(count(*) FILTER (WHERE correct)::NUMERIC / NULLIF(count(*), 0), 4) AS acceptance_rate
            FROM review_flags
           GROUP BY dimension
      ) aggregate
), review_summary AS (
    SELECT
        count(DISTINCT review.id)::INTEGER AS reviewed,
        count(flag.correct)::INTEGER AS reviewed_fields,
        count(flag.correct) FILTER (WHERE flag.correct)::INTEGER AS accepted_fields,
        round(count(flag.correct) FILTER (WHERE flag.correct)::NUMERIC / NULLIF(count(flag.correct), 0), 4) AS field_acceptance_rate
      FROM classification_validation_reviews review
      JOIN period_videos video ON video.id = review.video_id
      LEFT JOIN review_flags flag ON flag.id = review.id
), confidence_summary AS (
    SELECT
        round(avg(ai_confidence), 4) AS average_confidence,
        count(*) FILTER (WHERE ai_confidence < config.confidence_floor)::INTEGER AS below_floor,
        round(count(*) FILTER (WHERE ai_confidence < config.confidence_floor)::NUMERIC / NULLIF(count(ai_confidence), 0), 4) AS below_floor_rate
      FROM latest_observations
      CROSS JOIN config
), metric_diagnostics AS (
    SELECT
        count(virality_score)::INTEGER AS scored,
        round(min(virality_score), 4) AS minimum,
        round(percentile_cont(0.10) WITHIN GROUP (ORDER BY virality_score)::NUMERIC, 4) AS p10,
        round(percentile_cont(0.50) WITHIN GROUP (ORDER BY virality_score)::NUMERIC, 4) AS median,
        round(percentile_cont(0.90) WITHIN GROUP (ORDER BY virality_score)::NUMERIC, 4) AS p90,
        round(max(virality_score), 4) AS maximum,
        round(count(*) FILTER (WHERE virality_score <= 1)::NUMERIC / NULLIF(count(virality_score), 0), 4) AS low_tail_rate,
        round(count(*) FILTER (WHERE virality_score >= 9)::NUMERIC / NULLIF(count(virality_score), 0), 4) AS high_tail_rate,
        count(velocity_percentile)::INTEGER AS velocity_available,
        count(engagement_percentile)::INTEGER AS engagement_available,
        count(outlier_percentile)::INTEGER AS outlier_available,
        count(views_percentile)::INTEGER AS views_available,
        count(freshness_score)::INTEGER AS freshness_available,
        round(corr(velocity_percentile::DOUBLE PRECISION, virality_score::DOUBLE PRECISION)::NUMERIC, 4) AS velocity_correlation,
        round(corr(engagement_percentile::DOUBLE PRECISION, virality_score::DOUBLE PRECISION)::NUMERIC, 4) AS engagement_correlation,
        round(corr(outlier_percentile::DOUBLE PRECISION, virality_score::DOUBLE PRECISION)::NUMERIC, 4) AS outlier_correlation,
        round(corr(views_percentile::DOUBLE PRECISION, virality_score::DOUBLE PRECISION)::NUMERIC, 4) AS views_correlation,
        round(corr(freshness_score::DOUBLE PRECISION, virality_score::DOUBLE PRECISION)::NUMERIC, 4) AS freshness_correlation
      FROM latest_observations
), monetization_diagnostics AS (
    SELECT
        count(monetization_score)::INTEGER AS scored,
        round(min(monetization_score), 4) AS minimum,
        round(percentile_cont(0.10) WITHIN GROUP (ORDER BY monetization_score)::NUMERIC, 4) AS p10,
        round(percentile_cont(0.50) WITHIN GROUP (ORDER BY monetization_score)::NUMERIC, 4) AS median,
        round(percentile_cont(0.90) WITHIN GROUP (ORDER BY monetization_score)::NUMERIC, 4) AS p90,
        round(max(monetization_score), 4) AS maximum,
        round(count(*) FILTER (WHERE monetization_score <= 1)::NUMERIC / NULLIF(count(monetization_score), 0), 4) AS low_tail_rate,
        round(count(*) FILTER (WHERE monetization_score >= 9)::NUMERIC / NULLIF(count(monetization_score), 0), 4) AS high_tail_rate
      FROM latest_observations
), required_categories AS (
    SELECT * FROM (VALUES
        (1, 'movie_tv_clips', 'Movie / TV Clips'),
        (2, 'curiosities', 'Curiosidades'),
        (3, 'quick_tutorials', 'Tutoriais'),
        (4, 'podcast_clips', 'Podcast Clips'),
        (5, 'technology', 'Tecnologia'),
        (6, 'storytelling', 'Storytelling')
    ) AS required(sort_order, slug, label)
), category_rows AS (
    SELECT
        required.sort_order,
        required.slug,
        required.label,
        statistic.period_start,
        statistic.period_end,
        statistic.sample_size,
        statistic.median_views,
        statistic.p75_views,
        statistic.p90_views,
        statistic.median_velocity,
        statistic.median_engagement,
        statistic.outlier_rate,
        statistic.median_virality,
        statistic.median_monetization,
        statistic.consistency_score,
        statistic.opportunity_score,
        statistic.trend_direction,
        (statistic.sample_size >= config.min_category_sample) AS sufficient_sample
      FROM required_categories required
      CROSS JOIN config
      CROSS JOIN bounds
      LEFT JOIN LATERAL (
          SELECT value.*
            FROM category_statistics value
           WHERE value.dimension_type = 'category'
             AND value.dimension_value = required.slug
             AND value.calculation_version = config.trend_version
             AND value.period_end <= bounds.period_end
           ORDER BY value.period_end DESC, value.id DESC
           LIMIT 1
      ) statistic ON TRUE
), category_comparison AS (
    SELECT
        count(*) FILTER (WHERE sufficient_sample)::INTEGER AS sufficient_categories,
        COALESCE(jsonb_agg(
            jsonb_build_object(
                'category', slug,
                'label', label,
                'period_start', period_start,
                'period_end', period_end,
                'sample_size', sample_size,
                'sufficient_sample', COALESCE(sufficient_sample, false),
                'median_views', median_views,
                'p75_views', p75_views,
                'p90_views', p90_views,
                'median_velocity', median_velocity,
                'median_engagement', median_engagement,
                'outlier_rate', outlier_rate,
                'virality_score', median_virality,
                'monetization_score', median_monetization,
                'consistency_score', consistency_score,
                'opportunity_score', opportunity_score,
                'trend_direction', trend_direction
            ) ORDER BY sort_order
        ), '[]'::JSONB) AS items
      FROM category_rows
), readiness AS (
    SELECT
        COALESCE(snapshot_summary.observation_days, 0) >= config.min_observation_days AS observation_ready,
        review_summary.reviewed >= config.min_classifier_reviews AS classifier_ready,
        category_comparison.sufficient_categories = 6 AS categories_ready,
        (
            snapshot_anomalies.views_decreased
            + snapshot_anomalies.likes_decreased
            + snapshot_anomalies.comments_decreased
            + snapshot_anomalies.cadence_gaps
            + snapshot_errors.terminal_events
        ) > 0 AS snapshot_attention,
        COALESCE(metric_diagnostics.low_tail_rate, 0) > config.score_tail_threshold
            OR COALESCE(metric_diagnostics.high_tail_rate, 0) > config.score_tail_threshold
            OR COALESCE(monetization_diagnostics.low_tail_rate, 0) > config.score_tail_threshold
            OR COALESCE(monetization_diagnostics.high_tail_rate, 0) > config.score_tail_threshold AS score_attention
      FROM config
      CROSS JOIN snapshot_summary
      CROSS JOIN snapshot_anomalies
      CROSS JOIN snapshot_errors
      CROSS JOIN review_summary
      CROSS JOIN category_comparison
      CROSS JOIN metric_diagnostics
      CROSS JOIN monetization_diagnostics
), status AS (
    SELECT CASE
        WHEN NOT observation_ready OR NOT classifier_ready OR NOT categories_ready THEN 'insufficient_data'
        WHEN snapshot_attention OR score_attention THEN 'needs_attention'
        ELSE 'ready_for_weight_review'
    END AS overall_status
      FROM readiness
), source_payload AS (
    SELECT jsonb_build_object(
        'schema_version', '1.0',
        'validation_version', config.validation_version,
        'status', status.overall_status,
        'period', jsonb_build_object(
            'start', bounds.period_start,
            'end', bounds.period_end,
            'closed_window', true
        ),
        'data_coverage', jsonb_build_object(
            'videos', coverage.videos,
            'classifications', coverage.classifications,
            'virality_scores', coverage.virality_scores,
            'monetization_scores', coverage.monetization_scores,
            'represented_categories', coverage.represented_categories,
            'observation_days', snapshot_summary.observation_days,
            'minimum_observation_days', config.min_observation_days,
            'sample_groups', jsonb_build_object(
                'recent_videos', provenance.recent_videos,
                'high_performance_videos', provenance.high_performance_videos,
                'recent_share', round(provenance.recent_share, 4),
                'high_performance_share', round(provenance.high_performance_share, 4)
            )
        ),
        'snapshot_quality', jsonb_build_object(
            'snapshots', snapshot_summary.snapshots,
            'tracked_videos', snapshot_summary.tracked_videos,
            'videos_with_follow_up', snapshot_summary.videos_with_follow_up,
            'comparable_pairs', snapshot_anomalies.comparable_pairs,
            'views_decreased', snapshot_anomalies.views_decreased,
            'likes_decreased', snapshot_anomalies.likes_decreased,
            'comments_decreased', snapshot_anomalies.comments_decreased,
            'cadence_gaps', snapshot_anomalies.cadence_gaps,
            'terminal_tracker_errors', snapshot_errors.terminal_events,
            'cadence_tolerance', config.cadence_tolerance
        ),
        'classifier_review', jsonb_build_object(
            'classified_videos', coverage.classifications,
            'manual_reviews', review_summary.reviewed,
            'minimum_reviews', config.min_classifier_reviews,
            'reviewed_fields', review_summary.reviewed_fields,
            'accepted_fields', review_summary.accepted_fields,
            'field_acceptance_rate', review_summary.field_acceptance_rate,
            'by_dimension', review_by_dimension.items,
            'average_ai_confidence', confidence_summary.average_confidence,
            'confidence_floor', config.confidence_floor,
            'below_confidence_floor', confidence_summary.below_floor,
            'below_confidence_floor_rate', confidence_summary.below_floor_rate
        ),
        'score_diagnostics', jsonb_build_object(
            'virality', jsonb_build_object(
                'scored', metric_diagnostics.scored,
                'minimum', metric_diagnostics.minimum,
                'p10', metric_diagnostics.p10,
                'median', metric_diagnostics.median,
                'p90', metric_diagnostics.p90,
                'maximum', metric_diagnostics.maximum,
                'low_tail_rate', metric_diagnostics.low_tail_rate,
                'high_tail_rate', metric_diagnostics.high_tail_rate,
                'component_availability', jsonb_build_object(
                    'velocity', metric_diagnostics.velocity_available,
                    'engagement', metric_diagnostics.engagement_available,
                    'outlier', metric_diagnostics.outlier_available,
                    'views', metric_diagnostics.views_available,
                    'freshness', metric_diagnostics.freshness_available
                ),
                'component_correlations', jsonb_build_object(
                    'velocity', metric_diagnostics.velocity_correlation,
                    'engagement', metric_diagnostics.engagement_correlation,
                    'outlier', metric_diagnostics.outlier_correlation,
                    'views', metric_diagnostics.views_correlation,
                    'freshness', metric_diagnostics.freshness_correlation
                )
            ),
            'monetization', jsonb_build_object(
                'scored', monetization_diagnostics.scored,
                'minimum', monetization_diagnostics.minimum,
                'p10', monetization_diagnostics.p10,
                'median', monetization_diagnostics.median,
                'p90', monetization_diagnostics.p90,
                'maximum', monetization_diagnostics.maximum,
                'low_tail_rate', monetization_diagnostics.low_tail_rate,
                'high_tail_rate', monetization_diagnostics.high_tail_rate
            ),
            'tail_rate_threshold', config.score_tail_threshold
        ),
        'category_comparison', jsonb_build_object(
            'hypothesis', 'movie_tv_clips_vs_other_formats',
            'minimum_sample_size', config.min_category_sample,
            'required_categories', 6,
            'sufficient_categories', category_comparison.sufficient_categories,
            'items', category_comparison.items
        ),
        'weight_review', jsonb_build_object(
            'decision', CASE status.overall_status
                WHEN 'insufficient_data' THEN 'hold_v1_collect_more_data'
                WHEN 'needs_attention' THEN 'hold_v1_resolve_distortions'
                ELSE 'eligible_for_manual_calibration'
            END,
            'automatic_adjustment_applied', false,
            'readiness', jsonb_build_object(
                'observation_period_ready', readiness.observation_ready,
                'classifier_review_ready', readiness.classifier_ready,
                'category_samples_ready', readiness.categories_ready,
                'snapshot_attention', readiness.snapshot_attention,
                'score_attention', readiness.score_attention
            ),
            'current_weights', jsonb_build_object(
                'virality', jsonb_build_object(
                    'velocity', config.virality_velocity_weight,
                    'engagement', config.virality_engagement_weight,
                    'outlier', config.virality_outlier_weight,
                    'views', config.virality_views_weight,
                    'freshness', config.virality_freshness_weight
                ),
                'opportunity', jsonb_build_object(
                    'virality', config.opportunity_virality_weight,
                    'monetization', config.opportunity_monetization_weight,
                    'consistency', config.opportunity_consistency_weight
                )
            )
        ),
        'methodology', jsonb_build_object(
            'video_window', 'published_at within [start,end)',
            'snapshot_policy', 'immutable observations with monotonicity and cadence diagnostics',
            'classifier_policy', 'human labels are stored separately and never overwrite AI output',
            'score_policy', 'weights remain unchanged until all readiness gates pass',
            'category_policy', 'latest compatible category bucket at or before validation end'
        )
    ) AS value
      FROM config
      CROSS JOIN bounds
      CROSS JOIN coverage
      CROSS JOIN snapshot_summary
      CROSS JOIN snapshot_anomalies
      CROSS JOIN snapshot_errors
      CROSS JOIN provenance
      CROSS JOIN review_summary
      CROSS JOIN review_by_dimension
      CROSS JOIN confidence_summary
      CROSS JOIN metric_diagnostics
      CROSS JOIN monetization_diagnostics
      CROSS JOIN category_comparison
      CROSS JOIN readiness
      CROSS JOIN status
), rendered AS (
    SELECT
        source_payload.value || jsonb_build_object(
            'generated_at', p_generated_at,
            'source_hash', md5(source_payload.value::TEXT)
        ) AS report_json,
        md5(source_payload.value::TEXT) AS source_hash
      FROM source_payload
)
SELECT
    bounds.period_start,
    bounds.period_end,
    p_generated_at,
    config.validation_version,
    status.overall_status,
    coverage.videos,
    review_summary.reviewed,
    rendered.report_json,
    rendered.source_hash
  FROM config
  CROSS JOIN bounds
  CROSS JOIN coverage
  CROSS JOIN review_summary
  CROSS JOIN status
  CROSS JOIN rendered;
$$;

COMMIT;
